//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Wednesday, January 29, 2020
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiFunctionSchema.
    /// </summary>
    public sealed class ApiFunctionSchemaDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiFunctionSchema_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiFunctionSchema_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@Id", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiFunctionSchemaBase oEntity = entity as ApiFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionSchema_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@SeqNum", DbType.Int32, (oEntity.SeqNum.HasValue ? (object)oEntity.SeqNum : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FunctionId", DbType.Guid, (oEntity.FunctionId.HasValue ? (object)oEntity.FunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@TravFieldName", DbType.String, oEntity.TravFieldName);
            database.AddInParameter(commandWrapper, "@ApiFieldName", DbType.String, oEntity.ApiFieldName);
            database.AddInParameter(commandWrapper, "@ValueTranslation", DbType.String, oEntity.ValueTranslation);
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes);
            database.AddInParameter(commandWrapper, "@FieldSetting", DbType.Byte, (oEntity.FieldSetting.HasValue ? (object)oEntity.FieldSetting : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ChildFunctionId", DbType.Guid, (oEntity.ChildFunctionId.HasValue ? (object)oEntity.ChildFunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@QueryColumnName", DbType.String, oEntity.QueryColumnName);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiFunctionSchemaBase oEntity = entity as ApiFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionSchema_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiFunctionSchemaBase oEntity = entity as ApiFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionSchema_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddOutParameter(commandWrapper, "@Id", DbType.Int64, 0);
            database.AddInParameter(commandWrapper, "@SeqNum", DbType.Int32, (oEntity.SeqNum.HasValue ? (object)oEntity.SeqNum : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FunctionId", DbType.Guid, (oEntity.FunctionId.HasValue ? (object)oEntity.FunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@TravFieldName", DbType.String, oEntity.TravFieldName);
            database.AddInParameter(commandWrapper, "@ApiFieldName", DbType.String, oEntity.ApiFieldName);
            database.AddInParameter(commandWrapper, "@ValueTranslation", DbType.String, oEntity.ValueTranslation);
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes);
            database.AddInParameter(commandWrapper, "@FieldSetting", DbType.Byte, (oEntity.FieldSetting.HasValue ? (object)oEntity.FieldSetting : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ChildFunctionId", DbType.Guid, (oEntity.ChildFunctionId.HasValue ? (object)oEntity.ChildFunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@QueryColumnName", DbType.String, oEntity.QueryColumnName);
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Id = (System.Int64)database.GetParameterValue(commandWrapper, "@Id");

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiFunctionSchema";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("SeqNum", typeof(System.Int32));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("FunctionID", typeof(System.Guid));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("TravFieldName", typeof(System.String));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("ApiFieldName", typeof(System.String));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("ValueTranslation", typeof(System.String));
            col5.AllowDBNull = true;
            DataColumn col6 = dataTable.Columns.Add("Notes", typeof(System.String));
            col6.AllowDBNull = true;
            DataColumn col7 = dataTable.Columns.Add("FieldSetting", typeof(System.Byte));
            col7.AllowDBNull = true;
            DataColumn col8 = dataTable.Columns.Add("ChildFunctionID", typeof(System.Guid));
            col8.AllowDBNull = true;
            DataColumn col9 = dataTable.Columns.Add("QueryColumnName", typeof(System.String));
            col9.AllowDBNull = true;
            DataColumn col10 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col10.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("SeqNum", "SeqNum");
            bulkCopy.ColumnMappings.Add("FunctionID", "FunctionID");
            bulkCopy.ColumnMappings.Add("TravFieldName", "TravFieldName");
            bulkCopy.ColumnMappings.Add("ApiFieldName", "ApiFieldName");
            bulkCopy.ColumnMappings.Add("ValueTranslation", "ValueTranslation");
            bulkCopy.ColumnMappings.Add("Notes", "Notes");
            bulkCopy.ColumnMappings.Add("FieldSetting", "FieldSetting");
            bulkCopy.ColumnMappings.Add("ChildFunctionID", "ChildFunctionID");
            bulkCopy.ColumnMappings.Add("QueryColumnName", "QueryColumnName");
            bulkCopy.ColumnMappings.Add("ts", "ts");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiFunctionSchemaBase entity = list.Current as ApiFunctionSchemaBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["ID"] = entity.Id;
                row["SeqNum"] = entity.SeqNum.HasValue ? (object)entity.SeqNum : System.DBNull.Value;
                row["FunctionID"] = entity.FunctionId.HasValue ? (object)entity.FunctionId : System.DBNull.Value;
                row["TravFieldName"] = entity.TravFieldName;
                row["ApiFieldName"] = entity.ApiFieldName;
                row["ValueTranslation"] = entity.ValueTranslation;
                row["Notes"] = entity.Notes;
                row["FieldSetting"] = entity.FieldSetting.HasValue ? (object)entity.FieldSetting : System.DBNull.Value;
                row["ChildFunctionID"] = entity.ChildFunctionId.HasValue ? (object)entity.ChildFunctionId : System.DBNull.Value;
                row["QueryColumnName"] = entity.QueryColumnName;
                row["ts"] = entity.Ts;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

