//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserTokenProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiUserTokenProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiUserTokenProviderBase<T> : EntityProviderBase<T>
        where T : ApiUserTokenBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiUserTokenDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.UserId = (System.Int64)reader["UserID"];
                    c.OriginalUserId = c.UserId;
                    c.RefreshToken = (reader.IsDBNull(reader.GetOrdinal("RefreshToken"))) ? null : (System.String)reader["RefreshToken"];
                    c.IssueTime = (reader.IsDBNull(reader.GetOrdinal("IssueTime"))) ? null : (System.DateTime?)reader["IssueTime"];
                    c.ExpireTime = (reader.IsDBNull(reader.GetOrdinal("ExpireTime"))) ? null : (System.DateTime?)reader["ExpireTime"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
