//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiUserFunction.
    /// </summary>
    public sealed class ApiUserFunctionDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiUserFunction_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiUserFunction_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@Id", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionBase oEntity = entity as ApiUserFunctionBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunction_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@UserId", DbType.Int64, (oEntity.UserId.HasValue ? (object)oEntity.UserId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FunctionId", DbType.Guid, (oEntity.FunctionId.HasValue ? (object)oEntity.FunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AccessExpireDate", DbType.DateTime, (oEntity.AccessExpireDate.HasValue ? (object)oEntity.AccessExpireDate : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionBase oEntity = entity as ApiUserFunctionBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunction_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionBase oEntity = entity as ApiUserFunctionBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunction_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddOutParameter(commandWrapper, "@Id", DbType.Int64, 0);
            database.AddInParameter(commandWrapper, "@UserId", DbType.Int64, (oEntity.UserId.HasValue ? (object)oEntity.UserId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FunctionId", DbType.Guid, (oEntity.FunctionId.HasValue ? (object)oEntity.FunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AccessExpireDate", DbType.DateTime, (oEntity.AccessExpireDate.HasValue ? (object)oEntity.AccessExpireDate : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Id = (System.Int64)database.GetParameterValue(commandWrapper, "@Id");

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiUserFunction";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("UserID", typeof(System.Int64));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("FunctionID", typeof(System.Guid));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("AccessExpireDate", typeof(System.DateTime));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("DateCreated", typeof(System.DateTime));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("DateModified", typeof(System.DateTime));
            col5.AllowDBNull = true;
            DataColumn col6 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col6.AllowDBNull = true;
            DataColumn col7 = dataTable.Columns.Add("ModifiedBy", typeof(System.String));
            col7.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("UserID", "UserID");
            bulkCopy.ColumnMappings.Add("FunctionID", "FunctionID");
            bulkCopy.ColumnMappings.Add("AccessExpireDate", "AccessExpireDate");
            bulkCopy.ColumnMappings.Add("DateCreated", "DateCreated");
            bulkCopy.ColumnMappings.Add("DateModified", "DateModified");
            bulkCopy.ColumnMappings.Add("ts", "ts");
            bulkCopy.ColumnMappings.Add("ModifiedBy", "ModifiedBy");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiUserFunctionBase entity = list.Current as ApiUserFunctionBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["ID"] = entity.Id;
                row["UserID"] = entity.UserId.HasValue ? (object)entity.UserId : System.DBNull.Value;
                row["FunctionID"] = entity.FunctionId.HasValue ? (object)entity.FunctionId : System.DBNull.Value;
                row["AccessExpireDate"] = entity.AccessExpireDate.HasValue ? (object)entity.AccessExpireDate : System.DBNull.Value;
                row["DateCreated"] = entity.DateCreated.HasValue ? (object)entity.DateCreated : System.DBNull.Value;
                row["DateModified"] = entity.DateModified.HasValue ? (object)entity.DateModified : System.DBNull.Value;
                row["ts"] = entity.Ts;
                row["ModifiedBy"] = entity.ModifiedBy;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

