//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Wednesday, January 29, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiFunctionSchema'.
    ///</summary>
    [Serializable]
    internal partial class ApiFunctionSchemaProvider : ApiFunctionSchemaProviderBase<ApiFunctionSchema>
    {
    }
}
