//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSI.TraverseApi.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSI.TraverseApi.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [{0}];
        ///
        ///IF NOT EXISTS (SELECT * FROM sys.sysusers WHERE [name] = N&apos;{1}&apos;) AND 1 != IS_SRVROLEMEMBER(&apos;sysadmin&apos;, N&apos;{1}&apos;)
        ///BEGIN
        ///	CREATE USER [{1}] FOR LOGIN [{1}];
        ///	EXEC sp_addrolemember N&apos;db_owner&apos;, N&apos;{1}&apos;;
        ///END
        ///
        ///USE [master];.
        /// </summary>
        public static string ApiAddTravMasterUser {
            get {
                return ResourceManager.GetString("ApiAddTravMasterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM sys.databases WHERE [name] = N&apos;{0}&apos;)
        ///BEGIN
        ///	CREATE DATABASE [{0}];
        ///	ALTER DATABASE [{0}] SET ENABLE_BROKER;
        ///END.
        /// </summary>
        public static string ApiCreateDatabase {
            get {
                return ResourceManager.GetString("ApiCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [{0}];
        ///
        ///IF NOT EXISTS (SELECT * FROM sys.tables WHERE [object_id] = OBJECT_ID(N&apos;[dbo].[ApiInfo]&apos;))
        ///BEGIN
        ///	CREATE TABLE [dbo].[ApiInfo] (
        ///		[ID] [int] NOT NULL,                --Only 1
        ///		[SysDb] [sysname] NULL,		--System Database from Installer
        ///		[Version] [nvarchar](20) NULL,		--Version Information from installer
        ///		[AuthorizeTimeout] [int] NULL,		--Default to 15 minutes; user set in installer
        ///		[AccessExpireHours] [int] NULL,		--Default to 12 hours; user set in installer
        ///		[RefreshExpireDays]  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApiCreateInfoTable {
            get {
                return ResourceManager.GetString("ApiCreateInfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 as [DBExists] FROM sys.databases WHERE [name] = {0}.
        /// </summary>
        public static string ApiDatabaseExits {
            get {
                return ResourceManager.GetString("ApiDatabaseExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @dbName as sysname, @sql nvarchar(max)
        ///
        ///CREATE TABLE #DatabaseList (DbName sysname)
        ///
        ///DECLARE dbSearch CURSOR FOR
        ///SELECT [name]
        ///FROM [master].sys.databases
        ///WHERE HAS_DBACCESS([name]) = 1
        ///
        ///OPEN dbSearch
        ///
        ///FETCH NEXT FROM dbSearch INTO @dbName
        ///
        ///WHILE @@FETCH_STATUS = 0
        ///BEGIN
        ///	SET @sql = N&apos;
        ///DECLARE @innerSql nvarchar(max)
        ///
        ///IF EXISTS (SELECT * FROM [&apos; + @dbName + &apos;].sys.tables WHERE [name] = &apos;&apos;ApiInfo&apos;&apos; AND [type] = &apos;&apos;U&apos;&apos;)
        ///BEGIN
        ///	SET @innerSql = &apos;&apos;
        ///	INSERT INTO #DatabaseList (DbName)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApiFunctionHeaderTable {
            get {
                return ResourceManager.GetString("ApiFunctionHeaderTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @dbName as sysname, @sql nvarchar(max)
        ///
        ///CREATE TABLE #DatabaseList (DbName sysname)
        ///
        ///DECLARE dbSearch CURSOR FOR
        ///SELECT [name]
        ///FROM [master].sys.databases
        ///WHERE HAS_DBACCESS([name]) = 1
        ///
        ///OPEN dbSearch
        ///
        ///FETCH NEXT FROM dbSearch INTO @dbName
        ///
        ///WHILE @@FETCH_STATUS = 0
        ///BEGIN
        ///	SET @sql = N&apos;
        ///DECLARE @innerSql nvarchar(max)
        ///
        ///IF EXISTS (SELECT * FROM [&apos; + @dbName + &apos;].sys.tables WHERE [name] = &apos;&apos;ApiInfo&apos;&apos; AND [type] = &apos;&apos;U&apos;&apos;)
        ///BEGIN
        ///	SET @innerSql = &apos;&apos;
        ///	INSERT INTO #DatabaseList (DbName)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApiFunctionSchemaTable {
            get {
                return ResourceManager.GetString("ApiFunctionSchemaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress.
        /// </summary>
        public static string DocDeliveryContactName {
            get {
                return ResourceManager.GetString("DocDeliveryContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DocDeliveryFieldName {
            get {
                return ResourceManager.GetString("DocDeliveryFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM ApiPwd.
        /// </summary>
        public static string DocDeliveryFormId {
            get {
                return ResourceManager.GetString("DocDeliveryFormId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DocDeliverySourceIdColumn {
            get {
                return ResourceManager.GetString("DocDeliverySourceIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ApiFunctionHeader WHERE ID = {0}
        ///INSERT INTO ApiFunctionHeader (ID, [Name], AppId, [Type], Notes, Scope, OverrideID)
        ///SELECT {0} As ID, {1} As [Name], {2} As AppId, {3} As [Type], {4} As Notes, {5} As Scope, {6} As OverrideID.
        /// </summary>
        public static string FunctionHeaderScript {
            get {
                return ResourceManager.GetString("FunctionHeaderScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ApiFunctionSchema WHERE FunctionID = {0}.
        /// </summary>
        public static string FunctionSchemaDeleteScript {
            get {
                return ResourceManager.GetString("FunctionSchemaDeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ApiFunctionSchema (SeqNum, FunctionID, [TravFieldName], ApiFieldName, ValueTranslation, Notes, FieldSetting, ChildFunctionID)
        ///SELECT {0} As SeqNum, {1} As FunctionID, {2} As TravFieldName, {3} As ApiFieldName, {4} As ValueTranslation, {5} As Notes, {6} As FieldSetting, {7} As ChildFunctionID.
        /// </summary>
        public static string FunctionSchemaScript {
            get {
                return ResourceManager.GetString("FunctionSchemaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE dbUpdate CURSOR FOR
        ///SELECT DbName 
        ///FROM #DatabaseList
        ///
        ///OPEN dbUpdate
        ///
        ///FETCH NEXT FROM dbUpdate INTO @dbName
        ///
        ///WHILE @@FETCH_STATUS = 0
        ///BEGIN
        ///	SET @sql = N&apos;
        ///	USE [&apos; + @dbName + N&apos;];
        ///
        ///{0}
        ///
        ///	USE [&apos; + DB_NAME() + &apos;];
        ///&apos;
        ///
        ///	EXEC (@sql)
        ///	FETCH NEXT FROM dbUpdate INTO @dbName
        ///END
        ///
        ///CLOSE dbUpdate
        ///DEALLOCATE dbUpdate
        ///
        ///DROP TABLE #DatabaseList;.
        /// </summary>
        public static string GenerateScript {
            get {
                return ResourceManager.GetString("GenerateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @dbName as sysname, @sql nvarchar(max)
        ///
        ///CREATE TABLE #DatabaseList (DbName sysname)
        ///
        ///DECLARE dbSearch CURSOR FOR
        ///SELECT [name]
        ///FROM [master].sys.databases
        ///WHERE HAS_DBACCESS([name]) = 1
        ///
        ///OPEN dbSearch
        ///
        ///FETCH NEXT FROM dbSearch INTO @dbName
        ///
        ///WHILE @@FETCH_STATUS = 0
        ///BEGIN
        ///	SET @sql = N&apos;
        ///DECLARE @innerSql nvarchar(max)
        ///
        ///IF EXISTS (SELECT * FROM [&apos; + @dbName + &apos;].sys.tables WHERE [name] = &apos;&apos;ApiInfo&apos;&apos; AND [type] = &apos;&apos;U&apos;&apos;)
        ///BEGIN
        ///	SET @innerSql = &apos;&apos;
        ///	INSERT INTO #DatabaseList (DbName)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RetrieveApiDbList {
            get {
                return ResourceManager.GetString("RetrieveApiDbList", resourceCulture);
            }
        }
    }
}
