//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiUserFunctionSchema.
    /// </summary>
    public sealed class ApiUserFunctionSchemaDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiUserFunctionSchema_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiUserFunctionSchema_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@Id", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionSchemaBase oEntity = entity as ApiUserFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionSchema_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, (oEntity.UserFunctionId.HasValue ? (object)oEntity.UserFunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FieldType", DbType.Byte, (oEntity.FieldType.HasValue ? (object)oEntity.FieldType : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes);
            database.AddInParameter(commandWrapper, "@FunctionSchemaId", DbType.Int64, (oEntity.FunctionSchemaId.HasValue ? (object)oEntity.FunctionSchemaId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@CustomFieldName", DbType.String, oEntity.CustomFieldName);
            database.AddInParameter(commandWrapper, "@ApiFieldName", DbType.String, oEntity.ApiFieldName);
            database.AddInParameter(commandWrapper, "@Hidden", DbType.Boolean, (oEntity.Hidden.HasValue ? (object)oEntity.Hidden : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DefaultValue", DbType.String, oEntity.DefaultValue);
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionSchemaBase oEntity = entity as ApiUserFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionSchema_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionSchemaBase oEntity = entity as ApiUserFunctionSchemaBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionSchema_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddOutParameter(commandWrapper, "@Id", DbType.Int64, 0);
            database.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, (oEntity.UserFunctionId.HasValue ? (object)oEntity.UserFunctionId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FieldType", DbType.Byte, (oEntity.FieldType.HasValue ? (object)oEntity.FieldType : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes);
            database.AddInParameter(commandWrapper, "@FunctionSchemaId", DbType.Int64, (oEntity.FunctionSchemaId.HasValue ? (object)oEntity.FunctionSchemaId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@CustomFieldName", DbType.String, oEntity.CustomFieldName);
            database.AddInParameter(commandWrapper, "@ApiFieldName", DbType.String, oEntity.ApiFieldName);
            database.AddInParameter(commandWrapper, "@Hidden", DbType.Boolean, (oEntity.Hidden.HasValue ? (object)oEntity.Hidden : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DefaultValue", DbType.String, oEntity.DefaultValue);
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Id = (System.Int64)database.GetParameterValue(commandWrapper, "@Id");

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiUserFunctionSchema";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("UserFunctionID", typeof(System.Int64));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("FieldType", typeof(System.Byte));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("Notes", typeof(System.String));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("FunctionSchemaID", typeof(System.Int64));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("CustomFieldName", typeof(System.String));
            col5.AllowDBNull = true;
            DataColumn col6 = dataTable.Columns.Add("ApiFieldName", typeof(System.String));
            col6.AllowDBNull = true;
            DataColumn col7 = dataTable.Columns.Add("Hidden", typeof(System.Boolean));
            col7.AllowDBNull = true;
            DataColumn col8 = dataTable.Columns.Add("DefaultValue", typeof(System.String));
            col8.AllowDBNull = true;
            DataColumn col9 = dataTable.Columns.Add("DateCreated", typeof(System.DateTime));
            col9.AllowDBNull = true;
            DataColumn col10 = dataTable.Columns.Add("DateModified", typeof(System.DateTime));
            col10.AllowDBNull = true;
            DataColumn col11 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col11.AllowDBNull = true;
            DataColumn col12 = dataTable.Columns.Add("ModifiedBy", typeof(System.String));
            col12.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("UserFunctionID", "UserFunctionID");
            bulkCopy.ColumnMappings.Add("FieldType", "FieldType");
            bulkCopy.ColumnMappings.Add("Notes", "Notes");
            bulkCopy.ColumnMappings.Add("FunctionSchemaID", "FunctionSchemaID");
            bulkCopy.ColumnMappings.Add("CustomFieldName", "CustomFieldName");
            bulkCopy.ColumnMappings.Add("ApiFieldName", "ApiFieldName");
            bulkCopy.ColumnMappings.Add("Hidden", "Hidden");
            bulkCopy.ColumnMappings.Add("DefaultValue", "DefaultValue");
            bulkCopy.ColumnMappings.Add("DateCreated", "DateCreated");
            bulkCopy.ColumnMappings.Add("DateModified", "DateModified");
            bulkCopy.ColumnMappings.Add("ts", "ts");
            bulkCopy.ColumnMappings.Add("ModifiedBy", "ModifiedBy");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiUserFunctionSchemaBase entity = list.Current as ApiUserFunctionSchemaBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["ID"] = entity.Id;
                row["UserFunctionID"] = entity.UserFunctionId.HasValue ? (object)entity.UserFunctionId : System.DBNull.Value;
                row["FieldType"] = entity.FieldType.HasValue ? (object)entity.FieldType : System.DBNull.Value;
                row["Notes"] = entity.Notes;
                row["FunctionSchemaID"] = entity.FunctionSchemaId.HasValue ? (object)entity.FunctionSchemaId : System.DBNull.Value;
                row["CustomFieldName"] = entity.CustomFieldName;
                row["ApiFieldName"] = entity.ApiFieldName;
                row["Hidden"] = entity.Hidden.HasValue ? (object)entity.Hidden : System.DBNull.Value;
                row["DefaultValue"] = entity.DefaultValue;
                row["DateCreated"] = entity.DateCreated.HasValue ? (object)entity.DateCreated : System.DBNull.Value;
                row["DateModified"] = entity.DateModified.HasValue ? (object)entity.DateModified : System.DBNull.Value;
                row["ts"] = entity.Ts;
                row["ModifiedBy"] = entity.ModifiedBy;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

