//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Wednesday, January 29, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiFunctionSchemaProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiFunctionSchemaProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiFunctionSchemaProviderBase<T> : EntityProviderBase<T>
        where T : ApiFunctionSchemaBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiFunctionSchemaDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.Id = (System.Int64)reader["ID"];
                    c.SeqNum = (reader.IsDBNull(reader.GetOrdinal("SeqNum"))) ? null : (System.Int32?)reader["SeqNum"];
                    c.FunctionId = (reader.IsDBNull(reader.GetOrdinal("FunctionID"))) ? null : (System.Guid?)reader["FunctionID"];
                    c.TravFieldName = (reader.IsDBNull(reader.GetOrdinal("TravFieldName"))) ? null : (System.String)reader["TravFieldName"];
                    c.ApiFieldName = (reader.IsDBNull(reader.GetOrdinal("ApiFieldName"))) ? null : (System.String)reader["ApiFieldName"];
                    c.ValueTranslation = (reader.IsDBNull(reader.GetOrdinal("ValueTranslation"))) ? null : (System.String)reader["ValueTranslation"];
                    c.Notes = (reader.IsDBNull(reader.GetOrdinal("Notes"))) ? null : (System.String)reader["Notes"];
                    c.FieldSetting = (reader.IsDBNull(reader.GetOrdinal("FieldSetting"))) ? null : (System.Byte?)reader["FieldSetting"];
                    c.ChildFunctionId = (reader.IsDBNull(reader.GetOrdinal("ChildFunctionID"))) ? null : (System.Guid?)reader["ChildFunctionID"];
                    c.QueryColumnName = (reader.IsDBNull(reader.GetOrdinal("QueryColumnName"))) ? null : (System.String)reader["QueryColumnName"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts"))) ? null : (System.Byte[])reader["ts"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
