//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUserFunction' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserFunctionEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUserFunction"</remarks>
        public System.Int64 Id;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// UserID : 
        /// </summary>
        public System.Int64? UserId = null;

        /// <summary>
        /// FunctionID : 
        /// </summary>
        public System.Guid? FunctionId = null;

        /// <summary>
        /// AccessExpireDate : 
        /// </summary>
        public System.DateTime? AccessExpireDate = null;

        /// <summary>
        /// DateCreated : 
        /// </summary>
        public System.DateTime? DateCreated = null;

        /// <summary>
        /// DateModified : 
        /// </summary>
        public System.DateTime? DateModified = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;

        /// <summary>
        /// ModifiedBy : 
        /// </summary>
        public System.String ModifiedBy = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserFunctionEntityData _tmp = new ApiUserFunctionEntityData();

            _tmp.Id = this.Id;

            _tmp.UserId = this.UserId;
            _tmp.FunctionId = this.FunctionId;
            _tmp.AccessExpireDate = this.AccessExpireDate;
            _tmp.DateCreated = this.DateCreated;
            _tmp.DateModified = this.DateModified;
            _tmp.Ts = this.Ts;
            _tmp.ModifiedBy = this.ModifiedBy;

            return _tmp;
        }

    }//End struct
}


