//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Thursday, February 20, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiInfo' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiInfoEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiInfo"</remarks>
        public System.Int32 Id;

        /// <summary>
        /// keep a copy of the original so it can be used for editable primary keys.
        /// </summary>
        public System.Int32 OriginalId;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// SysDb : 
        /// </summary>
        public System.String SysDb = null;

        /// <summary>
        /// Version : 
        /// </summary>
        public System.String Version = null;

        /// <summary>
        /// AuthorizeTimeout : 
        /// </summary>
        public System.Int32? AuthorizeTimeout = null;

        /// <summary>
        /// AccessExpireHours : 
        /// </summary>
        public System.Int32? AccessExpireHours = null;

        /// <summary>
        /// RefreshExpireDays : 
        /// </summary>
        public System.Int32? RefreshExpireDays = null;

        /// <summary>
        /// IsDebugLocalEnv : 
        /// </summary>
        public System.Boolean? IsDebugLocalEnv = null;

        /// <summary>
        /// IgnoreInvalidField : 
        /// </summary>
        public System.Boolean? IgnoreInvalidField = null;

        /// <summary>
        /// UseMsgSecurity : 
        /// </summary>
        public System.Boolean? UseMsgSecurity = null;

        /// <summary>
        /// MsgSharedKey : 
        /// </summary>
        public System.String MsgSharedKey = null;

        /// <summary>
        /// MsgEncryption : 
        /// </summary>
        public System.Byte? MsgEncryption = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiInfoEntityData _tmp = new ApiInfoEntityData();

            _tmp.Id = this.Id;
            _tmp.OriginalId = this.OriginalId;

            _tmp.SysDb = this.SysDb;
            _tmp.Version = this.Version;
            _tmp.AuthorizeTimeout = this.AuthorizeTimeout;
            _tmp.AccessExpireHours = this.AccessExpireHours;
            _tmp.RefreshExpireDays = this.RefreshExpireDays;
            _tmp.IsDebugLocalEnv = this.IsDebugLocalEnv;
            _tmp.IgnoreInvalidField = this.IgnoreInvalidField;
            _tmp.UseMsgSecurity = this.UseMsgSecurity;
            _tmp.MsgSharedKey = this.MsgSharedKey;
            _tmp.MsgEncryption = this.MsgEncryption;
            _tmp.Ts = this.Ts;

            return _tmp;
        }

    }//End struct
}


