//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Thursday, February 20, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiInfo.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiInfo'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiInfoBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiInfoEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiInfoEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiInfoBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiInfoEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is int.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, false, false)]
        public virtual System.Int32 Id
        {
            get
            {
                return this.entityData.Id;
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;

                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }

        /// <summary>
        ///Get the original value of the ID property.
        /// </summary>
        /// <remarks>This is the original value of the ID property.</remarks>
        /// <value>This type is int</value>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public virtual System.Int32 OriginalId
        {
            get { return this.entityData.OriginalId; }
            set { this.entityData.OriginalId = value; }
        }

        /// <summary>
        /// Gets or sets the database field SysDb. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 128)]
        public virtual System.String SysDb
        {
            get
            {
                return this.entityData.SysDb;
            }
            set
            {
                if (this.entityData.SysDb == value)
                    return;

                OnColumnChanging("SysDb");
                this.entityData.SysDb = value;
                OnColumnChanged("SysDb");
                OnPropertyChanged("SysDb");
            }
        }

        /// <summary>
        /// Gets or sets the database field Version. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 20)]
        public virtual System.String Version
        {
            get
            {
                return this.entityData.Version;
            }
            set
            {
                if (this.entityData.Version == value)
                    return;

                OnColumnChanging("Version");
                this.entityData.Version = value;
                OnColumnChanged("Version");
                OnPropertyChanged("Version");
            }
        }

        /// <summary>
        /// Gets or sets the database field AuthorizeTimeout. 
        /// </summary>
        /// <value>This type is int.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int32? AuthorizeTimeout
        {
            get
            {
                return this.entityData.AuthorizeTimeout;
            }
            set
            {
                if (this.entityData.AuthorizeTimeout == value && this.entityData.AuthorizeTimeout != null)
                    return;

                OnColumnChanging("AuthorizeTimeout");
                this.entityData.AuthorizeTimeout = value;
                OnColumnChanged("AuthorizeTimeout");
                OnPropertyChanged("AuthorizeTimeout");
            }
        }

        /// <summary>
        /// Gets or sets the database field AccessExpireHours. 
        /// </summary>
        /// <value>This type is int.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int32? AccessExpireHours
        {
            get
            {
                return this.entityData.AccessExpireHours;
            }
            set
            {
                if (this.entityData.AccessExpireHours == value && this.entityData.AccessExpireHours != null)
                    return;

                OnColumnChanging("AccessExpireHours");
                this.entityData.AccessExpireHours = value;
                OnColumnChanged("AccessExpireHours");
                OnPropertyChanged("AccessExpireHours");
            }
        }

        /// <summary>
        /// Gets or sets the database field RefreshExpireDays. 
        /// </summary>
        /// <value>This type is int.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int32? RefreshExpireDays
        {
            get
            {
                return this.entityData.RefreshExpireDays;
            }
            set
            {
                if (this.entityData.RefreshExpireDays == value && this.entityData.RefreshExpireDays != null)
                    return;

                OnColumnChanging("RefreshExpireDays");
                this.entityData.RefreshExpireDays = value;
                OnColumnChanged("RefreshExpireDays");
                OnPropertyChanged("RefreshExpireDays");
            }
        }

        /// <summary>
        /// Gets or sets the database field IsDebugLocalEnv. 
        /// </summary>
        /// <value>This type is bit.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Boolean? IsDebugLocalEnv
        {
            get
            {
                return this.entityData.IsDebugLocalEnv;
            }
            set
            {
                if (this.entityData.IsDebugLocalEnv == value && this.entityData.IsDebugLocalEnv != null)
                    return;

                OnColumnChanging("IsDebugLocalEnv");
                this.entityData.IsDebugLocalEnv = value;
                OnColumnChanged("IsDebugLocalEnv");
                OnPropertyChanged("IsDebugLocalEnv");
            }
        }

        /// <summary>
        /// Gets or sets the database field IgnoreInvalidField. 
        /// </summary>
        /// <value>This type is bit.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Boolean? IgnoreInvalidField
        {
            get
            {
                return this.entityData.IgnoreInvalidField;
            }
            set
            {
                if (this.entityData.IgnoreInvalidField == value && this.entityData.IgnoreInvalidField != null)
                    return;

                OnColumnChanging("IgnoreInvalidField");
                this.entityData.IgnoreInvalidField = value;
                OnColumnChanged("IgnoreInvalidField");
                OnPropertyChanged("IgnoreInvalidField");
            }
        }

        /// <summary>
        /// Gets or sets the database field UseMsgSecurity. 
        /// </summary>
        /// <value>This type is bit.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Boolean? UseMsgSecurity
        {
            get
            {
                return this.entityData.UseMsgSecurity;
            }
            set
            {
                if (this.entityData.UseMsgSecurity == value && this.entityData.UseMsgSecurity != null)
                    return;

                OnColumnChanging("UseMsgSecurity");
                this.entityData.UseMsgSecurity = value;
                OnColumnChanged("UseMsgSecurity");
                OnPropertyChanged("UseMsgSecurity");
            }
        }

        /// <summary>
        /// Gets or sets the database field MsgSharedKey. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String MsgSharedKey
        {
            get
            {
                return this.entityData.MsgSharedKey;
            }
            set
            {
                if (this.entityData.MsgSharedKey == value)
                    return;

                OnColumnChanging("MsgSharedKey");
                this.entityData.MsgSharedKey = value;
                OnColumnChanged("MsgSharedKey");
                OnPropertyChanged("MsgSharedKey");
            }
        }

        /// <summary>
        /// Gets or sets the database field MsgEncryption. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? MsgEncryption
        {
            get
            {
                return this.entityData.MsgEncryption;
            }
            set
            {
                if (this.entityData.MsgEncryption == value && this.entityData.MsgEncryption != null)
                    return;

                OnColumnChanging("MsgEncryption");
                this.entityData.MsgEncryption = value;
                OnColumnChanged("MsgEncryption");
                OnPropertyChanged("MsgEncryption");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiInfo"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "ID", "SysDb", "Version", "AuthorizeTimeout", "AccessExpireHours", "RefreshExpireDays", "IsDebugLocalEnv", "IgnoreInvalidField", "UseMsgSecurity", "MsgSharedKey", "MsgEncryption", "ts" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "ID" }; }
        }
        #region ApiInfoColumn Enum

        /// <summary>
        /// Enumerate the ApiInfo columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
            Id,
            [EnumTextValue("SysDb")]
            [ColumnEnum("SysDb", typeof(System.String), System.Data.DbType.String, false, false, true, 128)]
            SysDb,
            [EnumTextValue("Version")]
            [ColumnEnum("Version", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
            Version,
            [EnumTextValue("AuthorizeTimeout")]
            [ColumnEnum("AuthorizeTimeout", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
            AuthorizeTimeout,
            [EnumTextValue("AccessExpireHours")]
            [ColumnEnum("AccessExpireHours", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
            AccessExpireHours,
            [EnumTextValue("RefreshExpireDays")]
            [ColumnEnum("RefreshExpireDays", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
            RefreshExpireDays,
            [EnumTextValue("IsDebugLocalEnv")]
            [ColumnEnum("IsDebugLocalEnv", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
            IsDebugLocalEnv,
            [EnumTextValue("IgnoreInvalidField")]
            [ColumnEnum("IgnoreInvalidField", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
            IgnoreInvalidField,
            [EnumTextValue("UseMsgSecurity")]
            [ColumnEnum("UseMsgSecurity", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
            UseMsgSecurity,
            [EnumTextValue("MsgSharedKey")]
            [ColumnEnum("MsgSharedKey", typeof(System.String), System.Data.DbType.String, false, false, true)]
            MsgSharedKey,
            [EnumTextValue("MsgEncryption")]
            [ColumnEnum("MsgEncryption", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            MsgEncryption,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts
        }//End enum

        #endregion ApiInfoColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("SysDb", 128));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("Version", 20));
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiInfoEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiInfoEntityData;
            }
        }
        #endregion

    }
}

