//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiUserFunction'.
    ///</summary>
    [Serializable]
    internal partial class ApiUserFunctionProvider : ApiUserFunctionProviderBase<ApiUserFunction>
    {
    }
}
