//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSI.TraverseApi.AccountsReceivable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSI.TraverseApi.AccountsReceivable.Resources.SQLStatements", typeof(SQLStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.[Counter], p.[CustId], p.[InvcNum], p.[CredMemNum], p.[RecType], p.[Status], CASE WHEN s.[AcctType] = 1
        /// THEN p.[AgingPeriod] ELSE NULL END AS [AgingPeriod], p.[DistCode], p.[TermsCode], p.[TransDate], p.[DiscDueDate], p.[NetDueDate], 
        /// SIGN(p.[RecType]) * p.[Amt] AS [Amt], SIGN(p.[RecType]) * p.[AmtFgn] AS [AmtFgn], SIGN(p.[RecType]) * p.[DiscAmt] AS [DiscAmt], 
        /// SIGN(p.[RecType]) * p.[DiscAmtFgn] AS [DiscAmtFgn], p.[PmtMethodId], p.[CheckNum], p.[JobId], p.[CurrencyId], p.[ExchRate], p.[GlPeri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArInvoices {
            get {
                return ResourceManager.GetString("ArInvoices", resourceCulture);
            }
        }
    }
}
