//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserFunctionAccessProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiUserFunctionAccessProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiUserFunctionAccessProviderBase<T> : EntityProviderBase<T>
        where T : ApiUserFunctionAccessBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiUserFunctionAccessDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.UserFunctionId = (System.Int64)reader["UserFunctionID"];
                    c.OriginalUserFunctionId = c.UserFunctionId;
                    c.AccessCount = (reader.IsDBNull(reader.GetOrdinal("AccessCount"))) ? null : (System.Int64?)reader["AccessCount"];
                    c.FirstAccessTime = (reader.IsDBNull(reader.GetOrdinal("FirstAccessTime"))) ? null : (System.DateTime?)reader["FirstAccessTime"];
                    c.LastAccessTime = (reader.IsDBNull(reader.GetOrdinal("LastAccessTime"))) ? null : (System.DateTime?)reader["LastAccessTime"];
                    c.LastAccessMethod = (reader.IsDBNull(reader.GetOrdinal("LastAccessMethod"))) ? null : (System.Byte?)reader["LastAccessMethod"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts"))) ? null : (System.Byte[])reader["ts"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
