//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserFunctionAccess'.
    ///</summary>
    [Serializable]
    public partial class ApiUserFunctionAccess : ApiUserFunctionAccessBase
    {
        #region Constructors
        /// <summary>
        /// This constructor is used for serialization purpose only.
        /// </summary>
        public ApiUserFunctionAccess() : base(null) { }
        /// <summary>
        /// Use this constructor by default.
        /// </summary>
        public ApiUserFunctionAccess(string compId)
            : base(compId)
        {
        }
        #endregion Constructors
    }
}
