//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUserFunctionAccess' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserFunctionAccessEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// UserFunctionID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUserFunctionAccess"</remarks>
        public System.Int64 UserFunctionId;

        /// <summary>
        /// keep a copy of the original so it can be used for editable primary keys.
        /// </summary>
        public System.Int64 OriginalUserFunctionId;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// AccessCount : 
        /// </summary>
        public System.Int64? AccessCount = null;

        /// <summary>
        /// FirstAccessTime : 
        /// </summary>
        public System.DateTime? FirstAccessTime = null;

        /// <summary>
        /// LastAccessTime : 
        /// </summary>
        public System.DateTime? LastAccessTime = null;

        /// <summary>
        /// LastAccessMethod : 
        /// </summary>
        public System.Byte? LastAccessMethod = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserFunctionAccessEntityData _tmp = new ApiUserFunctionAccessEntityData();

            _tmp.UserFunctionId = this.UserFunctionId;
            _tmp.OriginalUserFunctionId = this.OriginalUserFunctionId;

            _tmp.AccessCount = this.AccessCount;
            _tmp.FirstAccessTime = this.FirstAccessTime;
            _tmp.LastAccessTime = this.LastAccessTime;
            _tmp.LastAccessMethod = this.LastAccessMethod;
            _tmp.Ts = this.Ts;

            return _tmp;
        }

    }//End struct
}


