//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserFunctionSchemaProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiUserFunctionSchemaProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiUserFunctionSchemaProviderBase<T> : EntityProviderBase<T>
        where T : ApiUserFunctionSchemaBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiUserFunctionSchemaDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.Id = (System.Int64)reader["ID"];
                    c.UserFunctionId = (reader.IsDBNull(reader.GetOrdinal("UserFunctionID"))) ? null : (System.Int64?)reader["UserFunctionID"];
                    c.FieldType = (reader.IsDBNull(reader.GetOrdinal("FieldType"))) ? null : (System.Byte?)reader["FieldType"];
                    c.Notes = (reader.IsDBNull(reader.GetOrdinal("Notes"))) ? null : (System.String)reader["Notes"];
                    c.FunctionSchemaId = (reader.IsDBNull(reader.GetOrdinal("FunctionSchemaID"))) ? null : (System.Int64?)reader["FunctionSchemaID"];
                    c.CustomFieldName = (reader.IsDBNull(reader.GetOrdinal("CustomFieldName"))) ? null : (System.String)reader["CustomFieldName"];
                    c.ApiFieldName = (reader.IsDBNull(reader.GetOrdinal("ApiFieldName"))) ? null : (System.String)reader["ApiFieldName"];
                    c.Hidden = (reader.IsDBNull(reader.GetOrdinal("Hidden"))) ? null : (System.Boolean?)reader["Hidden"];
                    c.DefaultValue = (reader.IsDBNull(reader.GetOrdinal("DefaultValue"))) ? null : (System.String)reader["DefaultValue"];
                    c.DateCreated = (reader.IsDBNull(reader.GetOrdinal("DateCreated"))) ? null : (System.DateTime?)reader["DateCreated"];
                    c.DateModified = (reader.IsDBNull(reader.GetOrdinal("DateModified"))) ? null : (System.DateTime?)reader["DateModified"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts"))) ? null : (System.Byte[])reader["ts"];
                    c.ModifiedBy = (reader.IsDBNull(reader.GetOrdinal("ModifiedBy"))) ? null : (System.String)reader["ModifiedBy"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
