//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Thursday, February 20, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiInfo'.
    ///</summary>
    [Serializable]
    public partial class ApiInfoProvider : ApiInfoProviderBase<ApiInfo>
    {
    }
}
