//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserToken'.
    ///</summary>
    [Serializable]
    public partial class ApiUserToken : ApiUserTokenBase
    {
        #region Constructors
        /// <summary>
        /// This constructor is used for serialization purpose only.
        /// </summary>
        public ApiUserToken() : base(null) { }
        /// <summary>
        /// Use this constructor by default.
        /// </summary>
        public ApiUserToken(string compId)
            : base(compId)
        {
        }
        #endregion Constructors
    }
}
