//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUserToken' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserTokenEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// UserID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUserToken"</remarks>
        public System.Int64 UserId;

        /// <summary>
        /// keep a copy of the original so it can be used for editable primary keys.
        /// </summary>
        public System.Int64 OriginalUserId;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// RefreshToken : 
        /// </summary>
        public System.String RefreshToken = null;

        /// <summary>
        /// IssueTime : 
        /// </summary>
        public System.DateTime? IssueTime = null;

        /// <summary>
        /// ExpireTime : 
        /// </summary>
        public System.DateTime? ExpireTime = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserTokenEntityData _tmp = new ApiUserTokenEntityData();

            _tmp.UserId = this.UserId;
            _tmp.OriginalUserId = this.OriginalUserId;

            _tmp.RefreshToken = this.RefreshToken;
            _tmp.IssueTime = this.IssueTime;
            _tmp.ExpireTime = this.ExpireTime;

            return _tmp;
        }

    }//End struct
}


