//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserToken.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserToken'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiUserTokenBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiUserTokenEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiUserTokenEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiUserTokenBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiUserTokenEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field UserID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, false, false)]
        public virtual System.Int64 UserId
        {
            get
            {
                return this.entityData.UserId;
            }
            set
            {
                if (!this.IsNew || this.entityData.UserId == value)
                    return;

                OnColumnChanging("UserId");
                this.entityData.UserId = value;
                OnColumnChanged("UserId");
                OnPropertyChanged("UserId");
            }
        }

        /// <summary>
        ///Get the original value of the UserID property.
        /// </summary>
        /// <remarks>This is the original value of the UserID property.</remarks>
        /// <value>This type is bigint</value>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public virtual System.Int64 OriginalUserId
        {
            get { return this.entityData.OriginalUserId; }
            set { this.entityData.OriginalUserId = value; }
        }

        /// <summary>
        /// Gets or sets the database field RefreshToken. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String RefreshToken
        {
            get
            {
                return this.entityData.RefreshToken;
            }
            set
            {
                if (this.entityData.RefreshToken == value)
                    return;

                OnColumnChanging("RefreshToken");
                this.entityData.RefreshToken = value;
                OnColumnChanged("RefreshToken");
                OnPropertyChanged("RefreshToken");
            }
        }

        /// <summary>
        /// Gets or sets the database field IssueTime. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? IssueTime
        {
            get
            {
                return this.entityData.IssueTime;
            }
            set
            {
                if (this.entityData.IssueTime == value && this.entityData.IssueTime != null)
                    return;

                OnColumnChanging("IssueTime");
                this.entityData.IssueTime = value;
                OnColumnChanged("IssueTime");
                OnPropertyChanged("IssueTime");
            }
        }

        /// <summary>
        /// Gets or sets the database field ExpireTime. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? ExpireTime
        {
            get
            {
                return this.entityData.ExpireTime;
            }
            set
            {
                if (this.entityData.ExpireTime == value && this.entityData.ExpireTime != null)
                    return;

                OnColumnChanging("ExpireTime");
                this.entityData.ExpireTime = value;
                OnColumnChanged("ExpireTime");
                OnPropertyChanged("ExpireTime");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiUserToken"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "UserID", "RefreshToken", "IssueTime", "ExpireTime" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "UserID" }; }
        }
        #region ApiUserTokenColumn Enum

        /// <summary>
        /// Enumerate the ApiUserToken columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("UserID")]
            [ColumnEnum("UserID", typeof(System.Int64), System.Data.DbType.Int64, true, false, false)]
            UserId,
            [EnumTextValue("RefreshToken")]
            [ColumnEnum("RefreshToken", typeof(System.String), System.Data.DbType.String, false, false, true)]
            RefreshToken,
            [EnumTextValue("IssueTime")]
            [ColumnEnum("IssueTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            IssueTime,
            [EnumTextValue("ExpireTime")]
            [ColumnEnum("ExpireTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            ExpireTime
        }//End enum

        #endregion ApiUserTokenColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiUserTokenEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiUserTokenEntityData;
            }
        }
        #endregion

    }
}

