//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiUser.
    /// </summary>
    public sealed class ApiUserDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiUser_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiUser_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@Id", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserBase oEntity = entity as ApiUserBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUser_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@OriginalId", DbType.Int64, oEntity.OriginalId);
            database.AddInParameter(commandWrapper, "@EmailAddress", DbType.String, oEntity.EmailAddress);
            database.AddInParameter(commandWrapper, "@Password", DbType.String, oEntity.Password);
            database.AddInParameter(commandWrapper, "@Name", DbType.String, oEntity.Name);
            database.AddInParameter(commandWrapper, "@Role", DbType.Byte, (oEntity.Role.HasValue ? (object)oEntity.Role : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Status", DbType.Byte, (oEntity.Status.HasValue ? (object)oEntity.Status : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ResetPassword", DbType.Boolean, (oEntity.ResetPassword.HasValue ? (object)oEntity.ResetPassword : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AdditionalInfo", DbType.String, oEntity.AdditionalInfo);
            database.AddInParameter(commandWrapper, "@ExpirationDate", DbType.DateTime, (oEntity.ExpirationDate.HasValue ? (object)oEntity.ExpirationDate : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ClientId", DbType.Guid, (oEntity.ClientId.HasValue ? (object)oEntity.ClientId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ClientSecret", DbType.String, oEntity.ClientSecret);
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");
            oEntity.OriginalId = oEntity.Id;

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserBase oEntity = entity as ApiUserBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUser_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserBase oEntity = entity as ApiUserBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUser_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int64, oEntity.Id);
            database.AddInParameter(commandWrapper, "@EmailAddress", DbType.String, oEntity.EmailAddress);
            database.AddInParameter(commandWrapper, "@Password", DbType.String, oEntity.Password);
            database.AddInParameter(commandWrapper, "@Name", DbType.String, oEntity.Name);
            database.AddInParameter(commandWrapper, "@Role", DbType.Byte, (oEntity.Role.HasValue ? (object)oEntity.Role : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Status", DbType.Byte, (oEntity.Status.HasValue ? (object)oEntity.Status : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ResetPassword", DbType.Boolean, (oEntity.ResetPassword.HasValue ? (object)oEntity.ResetPassword : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AdditionalInfo", DbType.String, oEntity.AdditionalInfo);
            database.AddInParameter(commandWrapper, "@ExpirationDate", DbType.DateTime, (oEntity.ExpirationDate.HasValue ? (object)oEntity.ExpirationDate : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ClientId", DbType.Guid, (oEntity.ClientId.HasValue ? (object)oEntity.ClientId : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ClientSecret", DbType.String, oEntity.ClientSecret);
            database.AddInParameter(commandWrapper, "@DateCreated", DbType.DateTime, (oEntity.DateCreated.HasValue ? (object)oEntity.DateCreated : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@DateModified", DbType.DateTime, (oEntity.DateModified.HasValue ? (object)oEntity.DateModified : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ModifiedBy", DbType.String, oEntity.ModifiedBy);
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.OriginalId = oEntity.Id;
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiUser";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("EmailAddress", typeof(System.String));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("Password", typeof(System.String));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("Name", typeof(System.String));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("Role", typeof(System.Byte));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("Status", typeof(System.Byte));
            col5.AllowDBNull = true;
            DataColumn col6 = dataTable.Columns.Add("ResetPassword", typeof(System.Boolean));
            col6.AllowDBNull = true;
            DataColumn col7 = dataTable.Columns.Add("AdditionalInfo", typeof(System.String));
            col7.AllowDBNull = true;
            DataColumn col8 = dataTable.Columns.Add("ExpirationDate", typeof(System.DateTime));
            col8.AllowDBNull = true;
            DataColumn col9 = dataTable.Columns.Add("ClientID", typeof(System.Guid));
            col9.AllowDBNull = true;
            DataColumn col10 = dataTable.Columns.Add("ClientSecret", typeof(System.String));
            col10.AllowDBNull = true;
            DataColumn col11 = dataTable.Columns.Add("DateCreated", typeof(System.DateTime));
            col11.AllowDBNull = true;
            DataColumn col12 = dataTable.Columns.Add("DateModified", typeof(System.DateTime));
            col12.AllowDBNull = true;
            DataColumn col13 = dataTable.Columns.Add("ModifiedBy", typeof(System.String));
            col13.AllowDBNull = true;
            DataColumn col14 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col14.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("EmailAddress", "EmailAddress");
            bulkCopy.ColumnMappings.Add("Password", "Password");
            bulkCopy.ColumnMappings.Add("Name", "Name");
            bulkCopy.ColumnMappings.Add("Role", "Role");
            bulkCopy.ColumnMappings.Add("Status", "Status");
            bulkCopy.ColumnMappings.Add("ResetPassword", "ResetPassword");
            bulkCopy.ColumnMappings.Add("AdditionalInfo", "AdditionalInfo");
            bulkCopy.ColumnMappings.Add("ExpirationDate", "ExpirationDate");
            bulkCopy.ColumnMappings.Add("ClientID", "ClientID");
            bulkCopy.ColumnMappings.Add("ClientSecret", "ClientSecret");
            bulkCopy.ColumnMappings.Add("DateCreated", "DateCreated");
            bulkCopy.ColumnMappings.Add("DateModified", "DateModified");
            bulkCopy.ColumnMappings.Add("ModifiedBy", "ModifiedBy");
            bulkCopy.ColumnMappings.Add("ts", "ts");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiUserBase entity = list.Current as ApiUserBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["ID"] = entity.Id;
                row["EmailAddress"] = entity.EmailAddress;
                row["Password"] = entity.Password;
                row["Name"] = entity.Name;
                row["Role"] = entity.Role.HasValue ? (object)entity.Role : System.DBNull.Value;
                row["Status"] = entity.Status.HasValue ? (object)entity.Status : System.DBNull.Value;
                row["ResetPassword"] = entity.ResetPassword.HasValue ? (object)entity.ResetPassword : System.DBNull.Value;
                row["AdditionalInfo"] = entity.AdditionalInfo;
                row["ExpirationDate"] = entity.ExpirationDate.HasValue ? (object)entity.ExpirationDate : System.DBNull.Value;
                row["ClientID"] = entity.ClientId.HasValue ? (object)entity.ClientId : System.DBNull.Value;
                row["ClientSecret"] = entity.ClientSecret;
                row["DateCreated"] = entity.DateCreated.HasValue ? (object)entity.DateCreated : System.DBNull.Value;
                row["DateModified"] = entity.DateModified.HasValue ? (object)entity.DateModified : System.DBNull.Value;
                row["ModifiedBy"] = entity.ModifiedBy;
                row["ts"] = entity.Ts;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

