//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Thursday, February 20, 2020
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiInfo.
    /// </summary>
    public sealed class ApiInfoDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiInfo_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiInfo_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@Id", DbType.Int32, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiInfoBase oEntity = entity as ApiInfoBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiInfo_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int32, oEntity.Id);
            database.AddInParameter(commandWrapper, "@OriginalId", DbType.Int32, oEntity.OriginalId);
            database.AddInParameter(commandWrapper, "@SysDb", DbType.String, oEntity.SysDb);
            database.AddInParameter(commandWrapper, "@Version", DbType.String, oEntity.Version);
            database.AddInParameter(commandWrapper, "@AuthorizeTimeout", DbType.Int32, (oEntity.AuthorizeTimeout.HasValue ? (object)oEntity.AuthorizeTimeout : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AccessExpireHours", DbType.Int32, (oEntity.AccessExpireHours.HasValue ? (object)oEntity.AccessExpireHours : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@RefreshExpireDays", DbType.Int32, (oEntity.RefreshExpireDays.HasValue ? (object)oEntity.RefreshExpireDays : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@IsDebugLocalEnv", DbType.Boolean, (oEntity.IsDebugLocalEnv.HasValue ? (object)oEntity.IsDebugLocalEnv : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@IgnoreInvalidField", DbType.Boolean, (oEntity.IgnoreInvalidField.HasValue ? (object)oEntity.IgnoreInvalidField : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@UseMsgSecurity", DbType.Boolean, (oEntity.UseMsgSecurity.HasValue ? (object)oEntity.UseMsgSecurity : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@MsgSharedKey", DbType.String, oEntity.MsgSharedKey);
            database.AddInParameter(commandWrapper, "@MsgEncryption", DbType.Byte, (oEntity.MsgEncryption.HasValue ? (object)oEntity.MsgEncryption : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");
            oEntity.OriginalId = oEntity.Id;

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiInfoBase oEntity = entity as ApiInfoBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiInfo_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Int32, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiInfoBase oEntity = entity as ApiInfoBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiInfo_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@Id", DbType.Int32, oEntity.Id);
            database.AddInParameter(commandWrapper, "@SysDb", DbType.String, oEntity.SysDb);
            database.AddInParameter(commandWrapper, "@Version", DbType.String, oEntity.Version);
            database.AddInParameter(commandWrapper, "@AuthorizeTimeout", DbType.Int32, (oEntity.AuthorizeTimeout.HasValue ? (object)oEntity.AuthorizeTimeout : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@AccessExpireHours", DbType.Int32, (oEntity.AccessExpireHours.HasValue ? (object)oEntity.AccessExpireHours : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@RefreshExpireDays", DbType.Int32, (oEntity.RefreshExpireDays.HasValue ? (object)oEntity.RefreshExpireDays : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@IsDebugLocalEnv", DbType.Boolean, (oEntity.IsDebugLocalEnv.HasValue ? (object)oEntity.IsDebugLocalEnv : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@IgnoreInvalidField", DbType.Boolean, (oEntity.IgnoreInvalidField.HasValue ? (object)oEntity.IgnoreInvalidField : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@UseMsgSecurity", DbType.Boolean, (oEntity.UseMsgSecurity.HasValue ? (object)oEntity.UseMsgSecurity : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@MsgSharedKey", DbType.String, oEntity.MsgSharedKey);
            database.AddInParameter(commandWrapper, "@MsgEncryption", DbType.Byte, (oEntity.MsgEncryption.HasValue ? (object)oEntity.MsgEncryption : System.DBNull.Value));
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.OriginalId = oEntity.Id;
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiInfo";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Int32));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("SysDb", typeof(System.String));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("Version", typeof(System.String));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("AuthorizeTimeout", typeof(System.Int32));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("AccessExpireHours", typeof(System.Int32));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("RefreshExpireDays", typeof(System.Int32));
            col5.AllowDBNull = true;
            DataColumn col6 = dataTable.Columns.Add("IsDebugLocalEnv", typeof(System.Boolean));
            col6.AllowDBNull = true;
            DataColumn col7 = dataTable.Columns.Add("IgnoreInvalidField", typeof(System.Boolean));
            col7.AllowDBNull = true;
            DataColumn col8 = dataTable.Columns.Add("UseMsgSecurity", typeof(System.Boolean));
            col8.AllowDBNull = true;
            DataColumn col9 = dataTable.Columns.Add("MsgSharedKey", typeof(System.String));
            col9.AllowDBNull = true;
            DataColumn col10 = dataTable.Columns.Add("MsgEncryption", typeof(System.Byte));
            col10.AllowDBNull = true;
            DataColumn col11 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col11.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("SysDb", "SysDb");
            bulkCopy.ColumnMappings.Add("Version", "Version");
            bulkCopy.ColumnMappings.Add("AuthorizeTimeout", "AuthorizeTimeout");
            bulkCopy.ColumnMappings.Add("AccessExpireHours", "AccessExpireHours");
            bulkCopy.ColumnMappings.Add("RefreshExpireDays", "RefreshExpireDays");
            bulkCopy.ColumnMappings.Add("IsDebugLocalEnv", "IsDebugLocalEnv");
            bulkCopy.ColumnMappings.Add("IgnoreInvalidField", "IgnoreInvalidField");
            bulkCopy.ColumnMappings.Add("UseMsgSecurity", "UseMsgSecurity");
            bulkCopy.ColumnMappings.Add("MsgSharedKey", "MsgSharedKey");
            bulkCopy.ColumnMappings.Add("MsgEncryption", "MsgEncryption");
            bulkCopy.ColumnMappings.Add("ts", "ts");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiInfoBase entity = list.Current as ApiInfoBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["ID"] = entity.Id;
                row["SysDb"] = entity.SysDb;
                row["Version"] = entity.Version;
                row["AuthorizeTimeout"] = entity.AuthorizeTimeout.HasValue ? (object)entity.AuthorizeTimeout : System.DBNull.Value;
                row["AccessExpireHours"] = entity.AccessExpireHours.HasValue ? (object)entity.AccessExpireHours : System.DBNull.Value;
                row["RefreshExpireDays"] = entity.RefreshExpireDays.HasValue ? (object)entity.RefreshExpireDays : System.DBNull.Value;
                row["IsDebugLocalEnv"] = entity.IsDebugLocalEnv.HasValue ? (object)entity.IsDebugLocalEnv : System.DBNull.Value;
                row["IgnoreInvalidField"] = entity.IgnoreInvalidField.HasValue ? (object)entity.IgnoreInvalidField : System.DBNull.Value;
                row["UseMsgSecurity"] = entity.UseMsgSecurity.HasValue ? (object)entity.UseMsgSecurity : System.DBNull.Value;
                row["MsgSharedKey"] = entity.MsgSharedKey;
                row["MsgEncryption"] = entity.MsgEncryption.HasValue ? (object)entity.MsgEncryption : System.DBNull.Value;
                row["ts"] = entity.Ts;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

