//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
#region using directives
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Core;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiFunctionHeader'.
    ///</summary>
    [Serializable]
    public partial class ApiFunctionHeader:ApiFunctionHeaderBase
    {
        #region Constructors
        /// <summary>
        /// This constructor is used for serialization purpose only.
        /// </summary>
        public ApiFunctionHeader() : base(null) { }
        /// <summary>
        /// Use this constructor by default.
        /// </summary>
        public ApiFunctionHeader(string compId)
            : base(compId)
        {
        }
        #endregion Constructors
    }
}
