//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiFunctionHeaderProvider.cs
#region Using directives
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Data;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiFunctionHeaderProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiFunctionHeaderProviderBase<T> : EntityProviderBase<T>
        where T : ApiFunctionHeaderBase, new()
    {
        private static IDataProvider _dataProvider = null;
        
        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiFunctionHeaderDataProvider");
        }
        #endregion "Helper"
        
        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }
            
            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done
            
                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);
            
                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.Id = (System.Guid)reader["ID"];
                    c.OriginalId = c.Id;
                    c.Name = (reader.IsDBNull(reader.GetOrdinal("Name")))?null:(System.String)reader["Name"];
                    c.AppId = (reader.IsDBNull(reader.GetOrdinal("AppId")))?null:(System.String)reader["AppId"];
                    c.Type = (reader.IsDBNull(reader.GetOrdinal("Type")))?null:(System.Byte?)reader["Type"];
                    c.Notes = (reader.IsDBNull(reader.GetOrdinal("Notes")))?null:(System.String)reader["Notes"];
                    c.Scope = (reader.IsDBNull(reader.GetOrdinal("Scope")))?null:(System.Byte?)reader["Scope"];
                    c.OverrideId = (reader.IsDBNull(reader.GetOrdinal("OverrideID")))?null:(System.Guid?)reader["OverrideID"];
                    c.QueryTableName = (reader.IsDBNull(reader.GetOrdinal("QueryTableName")))?null:(System.String)reader["QueryTableName"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts")))?null:(System.Byte[])reader["ts"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
