//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;		
#endregion
namespace OSI.TraverseApi.Business
{
	///<summary>
	///The data structure representation of the 'ApiFunctionHeader' table.
	///</summary>
	///<remarks>
	///This struct is generated by a tool and should never be modified.
	///</remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal class ApiFunctionHeaderEntityData : ICloneable
	{
		#region Variable Declarations
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "ApiFunctionHeader"</remarks>
			public System.Guid Id;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Guid OriginalId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		public System.String  Name = null;
		
		/// <summary>
		/// AppId : 
		/// </summary>
		public System.String  AppId = null;
		
		/// <summary>
		/// Type : 
		/// </summary>
		public System.Byte?  Type = null;
		
		/// <summary>
		/// Notes : 
		/// </summary>
		public System.String  Notes = null;
		
		/// <summary>
		/// Scope : 
		/// </summary>
		public System.Byte?  Scope = null;
		
		/// <summary>
		/// OverrideID : 
		/// </summary>
		public System.Guid?  OverrideId = null;
		
		/// <summary>
		/// QueryTableName : 
		/// </summary>
		public System.String  QueryTableName = null;
		
		/// <summary>
		/// ts : 
		/// </summary>
		public System.Byte[]  Ts = null;
		#endregion
			
		#endregion "Variable Declarations"
		
		public Object Clone()
		{
			ApiFunctionHeaderEntityData _tmp = new ApiFunctionHeaderEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.Name = this.Name;
			_tmp.AppId = this.AppId;
			_tmp.Type = this.Type;
			_tmp.Notes = this.Notes;
			_tmp.Scope = this.Scope;
			_tmp.OverrideId = this.OverrideId;
			_tmp.QueryTableName = this.QueryTableName;
			_tmp.Ts = this.Ts;
			
			return _tmp;
		}
		
	}//End struct
}


