//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserFunctionSchema.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserFunctionSchema'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiUserFunctionSchemaBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiUserFunctionSchemaEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiUserFunctionSchemaEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiUserFunctionSchemaBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiUserFunctionSchemaEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [ReadOnlyAttribute(false), DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, true, false)]
        public virtual System.Int64 Id
        {
            get
            {
                return this.entityData.Id;
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;

                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Gets or sets the database field UserFunctionID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int64? UserFunctionId
        {
            get
            {
                return this.entityData.UserFunctionId;
            }
            set
            {
                if (this.entityData.UserFunctionId == value && this.entityData.UserFunctionId != null)
                    return;

                OnColumnChanging("UserFunctionId");
                this.entityData.UserFunctionId = value;
                OnColumnChanged("UserFunctionId");
                OnPropertyChanged("UserFunctionId");
            }
        }

        /// <summary>
        /// Gets or sets the database field FieldType. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? FieldType
        {
            get
            {
                return this.entityData.FieldType;
            }
            set
            {
                if (this.entityData.FieldType == value && this.entityData.FieldType != null)
                    return;

                OnColumnChanging("FieldType");
                this.entityData.FieldType = value;
                OnColumnChanged("FieldType");
                OnPropertyChanged("FieldType");
            }
        }

        /// <summary>
        /// Gets or sets the database field Notes. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String Notes
        {
            get
            {
                return this.entityData.Notes;
            }
            set
            {
                if (this.entityData.Notes == value)
                    return;

                OnColumnChanging("Notes");
                this.entityData.Notes = value;
                OnColumnChanged("Notes");
                OnPropertyChanged("Notes");
            }
        }

        /// <summary>
        /// Gets or sets the database field FunctionSchemaID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int64? FunctionSchemaId
        {
            get
            {
                return this.entityData.FunctionSchemaId;
            }
            set
            {
                if (this.entityData.FunctionSchemaId == value && this.entityData.FunctionSchemaId != null)
                    return;

                OnColumnChanging("FunctionSchemaId");
                this.entityData.FunctionSchemaId = value;
                OnColumnChanged("FunctionSchemaId");
                OnPropertyChanged("FunctionSchemaId");
            }
        }

        /// <summary>
        /// Gets or sets the database field CustomFieldName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 100)]
        public virtual System.String CustomFieldName
        {
            get
            {
                return this.entityData.CustomFieldName;
            }
            set
            {
                if (this.entityData.CustomFieldName == value)
                    return;

                OnColumnChanging("CustomFieldName");
                this.entityData.CustomFieldName = value;
                OnColumnChanged("CustomFieldName");
                OnPropertyChanged("CustomFieldName");
            }
        }

        /// <summary>
        /// Gets or sets the database field ApiFieldName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 128)]
        public virtual System.String ApiFieldName
        {
            get
            {
                return this.entityData.ApiFieldName;
            }
            set
            {
                if (this.entityData.ApiFieldName == value)
                    return;

                OnColumnChanging("ApiFieldName");
                this.entityData.ApiFieldName = value;
                OnColumnChanged("ApiFieldName");
                OnPropertyChanged("ApiFieldName");
            }
        }

        /// <summary>
        /// Gets or sets the database field Hidden. 
        /// </summary>
        /// <value>This type is bit.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Boolean? Hidden
        {
            get
            {
                return this.entityData.Hidden;
            }
            set
            {
                if (this.entityData.Hidden == value && this.entityData.Hidden != null)
                    return;

                OnColumnChanging("Hidden");
                this.entityData.Hidden = value;
                OnColumnChanged("Hidden");
                OnPropertyChanged("Hidden");
            }
        }

        /// <summary>
        /// Gets or sets the database field DefaultValue. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String DefaultValue
        {
            get
            {
                return this.entityData.DefaultValue;
            }
            set
            {
                if (this.entityData.DefaultValue == value)
                    return;

                OnColumnChanging("DefaultValue");
                this.entityData.DefaultValue = value;
                OnColumnChanged("DefaultValue");
                OnPropertyChanged("DefaultValue");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateCreated. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateCreated
        {
            get
            {
                return this.entityData.DateCreated;
            }
            set
            {
                if (this.entityData.DateCreated == value && this.entityData.DateCreated != null)
                    return;

                OnColumnChanging("DateCreated");
                this.entityData.DateCreated = value;
                OnColumnChanged("DateCreated");
                OnPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateModified. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateModified
        {
            get
            {
                return this.entityData.DateModified;
            }
            set
            {
                if (this.entityData.DateModified == value && this.entityData.DateModified != null)
                    return;

                OnColumnChanging("DateModified");
                this.entityData.DateModified = value;
                OnColumnChanged("DateModified");
                OnPropertyChanged("DateModified");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        /// <summary>
        /// Gets or sets the database field ModifiedBy. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 100)]
        public virtual System.String ModifiedBy
        {
            get
            {
                return this.entityData.ModifiedBy;
            }
            set
            {
                if (this.entityData.ModifiedBy == value)
                    return;

                OnColumnChanging("ModifiedBy");
                this.entityData.ModifiedBy = value;
                OnColumnChanged("ModifiedBy");
                OnPropertyChanged("ModifiedBy");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiUserFunctionSchema"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "ID", "UserFunctionID", "FieldType", "Notes", "FunctionSchemaID", "CustomFieldName", "ApiFieldName", "Hidden", "DefaultValue", "DateCreated", "DateModified", "ts", "ModifiedBy" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "ID" }; }
        }
        #region ApiUserFunctionSchemaColumn Enum

        /// <summary>
        /// Enumerate the ApiUserFunctionSchema columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
            Id,
            [EnumTextValue("UserFunctionID")]
            [ColumnEnum("UserFunctionID", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
            UserFunctionId,
            [EnumTextValue("FieldType")]
            [ColumnEnum("FieldType", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            FieldType,
            [EnumTextValue("Notes")]
            [ColumnEnum("Notes", typeof(System.String), System.Data.DbType.String, false, false, true)]
            Notes,
            [EnumTextValue("FunctionSchemaID")]
            [ColumnEnum("FunctionSchemaID", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
            FunctionSchemaId,
            [EnumTextValue("CustomFieldName")]
            [ColumnEnum("CustomFieldName", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
            CustomFieldName,
            [EnumTextValue("ApiFieldName")]
            [ColumnEnum("ApiFieldName", typeof(System.String), System.Data.DbType.String, false, false, true, 128)]
            ApiFieldName,
            [EnumTextValue("Hidden")]
            [ColumnEnum("Hidden", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
            Hidden,
            [EnumTextValue("DefaultValue")]
            [ColumnEnum("DefaultValue", typeof(System.String), System.Data.DbType.String, false, false, true)]
            DefaultValue,
            [EnumTextValue("DateCreated")]
            [ColumnEnum("DateCreated", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateCreated,
            [EnumTextValue("DateModified")]
            [ColumnEnum("DateModified", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateModified,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts,
            [EnumTextValue("ModifiedBy")]
            [ColumnEnum("ModifiedBy", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
            ModifiedBy
        }//End enum

        #endregion ApiUserFunctionSchemaColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("CustomFieldName", 100));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("ApiFieldName", 128));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("ModifiedBy", 100));
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiUserFunctionSchemaEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiUserFunctionSchemaEntityData;
            }
        }
        #endregion

    }
}

