//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUserFunctionSchema' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserFunctionSchemaEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUserFunctionSchema"</remarks>
        public System.Int64 Id;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// UserFunctionID : 
        /// </summary>
        public System.Int64? UserFunctionId = null;

        /// <summary>
        /// FieldType : 
        /// </summary>
        public System.Byte? FieldType = null;

        /// <summary>
        /// Notes : 
        /// </summary>
        public System.String Notes = null;

        /// <summary>
        /// FunctionSchemaID : 
        /// </summary>
        public System.Int64? FunctionSchemaId = null;

        /// <summary>
        /// CustomFieldName : 
        /// </summary>
        public System.String CustomFieldName = null;

        /// <summary>
        /// ApiFieldName : 
        /// </summary>
        public System.String ApiFieldName = null;

        /// <summary>
        /// Hidden : 
        /// </summary>
        public System.Boolean? Hidden = null;

        /// <summary>
        /// DefaultValue : 
        /// </summary>
        public System.String DefaultValue = null;

        /// <summary>
        /// DateCreated : 
        /// </summary>
        public System.DateTime? DateCreated = null;

        /// <summary>
        /// DateModified : 
        /// </summary>
        public System.DateTime? DateModified = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;

        /// <summary>
        /// ModifiedBy : 
        /// </summary>
        public System.String ModifiedBy = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserFunctionSchemaEntityData _tmp = new ApiUserFunctionSchemaEntityData();

            _tmp.Id = this.Id;

            _tmp.UserFunctionId = this.UserFunctionId;
            _tmp.FieldType = this.FieldType;
            _tmp.Notes = this.Notes;
            _tmp.FunctionSchemaId = this.FunctionSchemaId;
            _tmp.CustomFieldName = this.CustomFieldName;
            _tmp.ApiFieldName = this.ApiFieldName;
            _tmp.Hidden = this.Hidden;
            _tmp.DefaultValue = this.DefaultValue;
            _tmp.DateCreated = this.DateCreated;
            _tmp.DateModified = this.DateModified;
            _tmp.Ts = this.Ts;
            _tmp.ModifiedBy = this.ModifiedBy;

            return _tmp;
        }

    }//End struct
}


