//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserFunctionComp'.
    ///</summary>
    [Serializable]
    public partial class ApiUserFunctionComp : ApiUserFunctionCompBase
    {
        #region Constructors
        /// <summary>
        /// This constructor is used for serialization purpose only.
        /// </summary>
        public ApiUserFunctionComp() : base(null) { }
        /// <summary>
        /// Use this constructor by default.
        /// </summary>
        public ApiUserFunctionComp(string compId)
            : base(compId)
        {
        }
        #endregion Constructors
    }
}
