//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserFunctionComp.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserFunctionComp'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiUserFunctionCompBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiUserFunctionCompEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiUserFunctionCompEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiUserFunctionCompBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiUserFunctionCompEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [ReadOnlyAttribute(false), DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, true, false)]
        public virtual System.Int64 Id
        {
            get
            {
                return this.entityData.Id;
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;

                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Gets or sets the database field UserFunctionID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int64? UserFunctionId
        {
            get
            {
                return this.entityData.UserFunctionId;
            }
            set
            {
                if (this.entityData.UserFunctionId == value && this.entityData.UserFunctionId != null)
                    return;

                OnColumnChanging("UserFunctionId");
                this.entityData.UserFunctionId = value;
                OnColumnChanged("UserFunctionId");
                OnPropertyChanged("UserFunctionId");
            }
        }

        /// <summary>
        /// Gets or sets the database field CompID. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 3)]
        public virtual System.String CompanyId
        {
            get
            {
                return this.entityData.CompanyId;
            }
            set
            {
                if (this.entityData.CompanyId == value)
                    return;

                OnColumnChanging("CompanyId");
                this.entityData.CompanyId = value;
                OnColumnChanged("CompanyId");
                OnPropertyChanged("CompanyId");
            }
        }

        /// <summary>
        /// Gets or sets the database field Scope. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? Scope
        {
            get
            {
                return this.entityData.Scope;
            }
            set
            {
                if (this.entityData.Scope == value && this.entityData.Scope != null)
                    return;

                OnColumnChanging("Scope");
                this.entityData.Scope = value;
                OnColumnChanged("Scope");
                OnPropertyChanged("Scope");
            }
        }

        /// <summary>
        /// Gets or sets the database field Filter. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String Filter
        {
            get
            {
                return this.entityData.Filter;
            }
            set
            {
                if (this.entityData.Filter == value)
                    return;

                OnColumnChanging("Filter");
                this.entityData.Filter = value;
                OnColumnChanged("Filter");
                OnPropertyChanged("Filter");
            }
        }

        /// <summary>
        /// Gets or sets the database field DisplayFilter. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String DisplayFilter
        {
            get
            {
                return this.entityData.DisplayFilter;
            }
            set
            {
                if (this.entityData.DisplayFilter == value)
                    return;

                OnColumnChanging("DisplayFilter");
                this.entityData.DisplayFilter = value;
                OnColumnChanged("DisplayFilter");
                OnPropertyChanged("DisplayFilter");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateCreated. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateCreated
        {
            get
            {
                return this.entityData.DateCreated;
            }
            set
            {
                if (this.entityData.DateCreated == value && this.entityData.DateCreated != null)
                    return;

                OnColumnChanging("DateCreated");
                this.entityData.DateCreated = value;
                OnColumnChanged("DateCreated");
                OnPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateModified. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateModified
        {
            get
            {
                return this.entityData.DateModified;
            }
            set
            {
                if (this.entityData.DateModified == value && this.entityData.DateModified != null)
                    return;

                OnColumnChanging("DateModified");
                this.entityData.DateModified = value;
                OnColumnChanged("DateModified");
                OnPropertyChanged("DateModified");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        /// <summary>
        /// Gets or sets the database field ModifiedBy. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 100)]
        public virtual System.String ModifiedBy
        {
            get
            {
                return this.entityData.ModifiedBy;
            }
            set
            {
                if (this.entityData.ModifiedBy == value)
                    return;

                OnColumnChanging("ModifiedBy");
                this.entityData.ModifiedBy = value;
                OnColumnChanged("ModifiedBy");
                OnPropertyChanged("ModifiedBy");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiUserFunctionComp"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "ID", "UserFunctionID", "CompID", "Scope", "Filter", "DisplayFilter", "DateCreated", "DateModified", "ts", "ModifiedBy" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "ID" }; }
        }
        #region ApiUserFunctionCompColumn Enum

        /// <summary>
        /// Enumerate the ApiUserFunctionComp columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
            Id,
            [EnumTextValue("UserFunctionID")]
            [ColumnEnum("UserFunctionID", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
            UserFunctionId,
            [EnumTextValue("CompID")]
            [ColumnEnum("CompID", typeof(System.String), System.Data.DbType.String, false, false, true, 3)]
            CompanyId,
            [EnumTextValue("Scope")]
            [ColumnEnum("Scope", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            Scope,
            [EnumTextValue("Filter")]
            [ColumnEnum("Filter", typeof(System.String), System.Data.DbType.String, false, false, true)]
            Filter,
            [EnumTextValue("DisplayFilter")]
            [ColumnEnum("DisplayFilter", typeof(System.String), System.Data.DbType.String, false, false, true)]
            DisplayFilter,
            [EnumTextValue("DateCreated")]
            [ColumnEnum("DateCreated", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateCreated,
            [EnumTextValue("DateModified")]
            [ColumnEnum("DateModified", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateModified,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts,
            [EnumTextValue("ModifiedBy")]
            [ColumnEnum("ModifiedBy", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
            ModifiedBy
        }//End enum

        #endregion ApiUserFunctionCompColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("CompanyId", 3));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("ModifiedBy", 100));
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiUserFunctionCompEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiUserFunctionCompEntityData;
            }
        }
        #endregion

    }
}

