//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Monday, January 20, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUserFunctionComp' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserFunctionCompEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUserFunctionComp"</remarks>
        public System.Int64 Id;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// UserFunctionID : 
        /// </summary>
        public System.Int64? UserFunctionId = null;

        /// <summary>
        /// CompID : 
        /// </summary>
        public System.String CompanyId = null;

        /// <summary>
        /// Scope : 
        /// </summary>
        public System.Byte? Scope = null;

        /// <summary>
        /// Filter : 
        /// </summary>
        public System.String Filter = null;

        /// <summary>
        /// DisplayFilter : 
        /// </summary>
        public System.String DisplayFilter = null;

        /// <summary>
        /// DateCreated : 
        /// </summary>
        public System.DateTime? DateCreated = null;

        /// <summary>
        /// DateModified : 
        /// </summary>
        public System.DateTime? DateModified = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;

        /// <summary>
        /// ModifiedBy : 
        /// </summary>
        public System.String ModifiedBy = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserFunctionCompEntityData _tmp = new ApiUserFunctionCompEntityData();

            _tmp.Id = this.Id;

            _tmp.UserFunctionId = this.UserFunctionId;
            _tmp.CompanyId = this.CompanyId;
            _tmp.Scope = this.Scope;
            _tmp.Filter = this.Filter;
            _tmp.DisplayFilter = this.DisplayFilter;
            _tmp.DateCreated = this.DateCreated;
            _tmp.DateModified = this.DateModified;
            _tmp.Ts = this.Ts;
            _tmp.ModifiedBy = this.ModifiedBy;

            return _tmp;
        }

    }//End struct
}


