//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Wednesday, January 29, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiFunctionSchema.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiFunctionSchema'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiFunctionSchemaBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiFunctionSchemaEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiFunctionSchemaEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiFunctionSchemaBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiFunctionSchemaEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [ReadOnlyAttribute(false), DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, true, false)]
        public virtual System.Int64 Id
        {
            get
            {
                return this.entityData.Id;
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;

                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Gets or sets the database field SeqNum. 
        /// </summary>
        /// <value>This type is int.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int32? SeqNum
        {
            get
            {
                return this.entityData.SeqNum;
            }
            set
            {
                if (this.entityData.SeqNum == value && this.entityData.SeqNum != null)
                    return;

                OnColumnChanging("SeqNum");
                this.entityData.SeqNum = value;
                OnColumnChanged("SeqNum");
                OnPropertyChanged("SeqNum");
            }
        }

        /// <summary>
        /// Gets or sets the database field FunctionID. 
        /// </summary>
        /// <value>This type is uniqueidentifier.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Guid? FunctionId
        {
            get
            {
                return this.entityData.FunctionId;
            }
            set
            {
                if (this.entityData.FunctionId == value && this.entityData.FunctionId != null)
                    return;

                OnColumnChanging("FunctionId");
                this.entityData.FunctionId = value;
                OnColumnChanged("FunctionId");
                OnPropertyChanged("FunctionId");
            }
        }

        /// <summary>
        /// Gets or sets the database field TravFieldName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 128)]
        public virtual System.String TravFieldName
        {
            get
            {
                return this.entityData.TravFieldName;
            }
            set
            {
                if (this.entityData.TravFieldName == value)
                    return;

                OnColumnChanging("TravFieldName");
                this.entityData.TravFieldName = value;
                OnColumnChanged("TravFieldName");
                OnPropertyChanged("TravFieldName");
            }
        }

        /// <summary>
        /// Gets or sets the database field ApiFieldName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 128)]
        public virtual System.String ApiFieldName
        {
            get
            {
                return this.entityData.ApiFieldName;
            }
            set
            {
                if (this.entityData.ApiFieldName == value)
                    return;

                OnColumnChanging("ApiFieldName");
                this.entityData.ApiFieldName = value;
                OnColumnChanged("ApiFieldName");
                OnPropertyChanged("ApiFieldName");
            }
        }

        /// <summary>
        /// Gets or sets the database field ValueTranslation. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String ValueTranslation
        {
            get
            {
                return this.entityData.ValueTranslation;
            }
            set
            {
                if (this.entityData.ValueTranslation == value)
                    return;

                OnColumnChanging("ValueTranslation");
                this.entityData.ValueTranslation = value;
                OnColumnChanged("ValueTranslation");
                OnPropertyChanged("ValueTranslation");
            }
        }

        /// <summary>
        /// Gets or sets the database field Notes. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String Notes
        {
            get
            {
                return this.entityData.Notes;
            }
            set
            {
                if (this.entityData.Notes == value)
                    return;

                OnColumnChanging("Notes");
                this.entityData.Notes = value;
                OnColumnChanged("Notes");
                OnPropertyChanged("Notes");
            }
        }

        /// <summary>
        /// Gets or sets the database field FieldSetting. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? FieldSetting
        {
            get
            {
                return this.entityData.FieldSetting;
            }
            set
            {
                if (this.entityData.FieldSetting == value && this.entityData.FieldSetting != null)
                    return;

                OnColumnChanging("FieldSetting");
                this.entityData.FieldSetting = value;
                OnColumnChanged("FieldSetting");
                OnPropertyChanged("FieldSetting");
            }
        }

        /// <summary>
        /// Gets or sets the database field ChildFunctionID. 
        /// </summary>
        /// <value>This type is uniqueidentifier.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Guid? ChildFunctionId
        {
            get
            {
                return this.entityData.ChildFunctionId;
            }
            set
            {
                if (this.entityData.ChildFunctionId == value && this.entityData.ChildFunctionId != null)
                    return;

                OnColumnChanging("ChildFunctionId");
                this.entityData.ChildFunctionId = value;
                OnColumnChanged("ChildFunctionId");
                OnPropertyChanged("ChildFunctionId");
            }
        }

        /// <summary>
        /// Gets or sets the database field QueryColumnName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 128)]
        public virtual System.String QueryColumnName
        {
            get
            {
                return this.entityData.QueryColumnName;
            }
            set
            {
                if (this.entityData.QueryColumnName == value)
                    return;

                OnColumnChanging("QueryColumnName");
                this.entityData.QueryColumnName = value;
                OnColumnChanged("QueryColumnName");
                OnPropertyChanged("QueryColumnName");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiFunctionSchema"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "ID", "SeqNum", "FunctionID", "TravFieldName", "ApiFieldName", "ValueTranslation", "Notes", "FieldSetting", "ChildFunctionID", "QueryColumnName", "ts" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "ID" }; }
        }
        #region ApiFunctionSchemaColumn Enum

        /// <summary>
        /// Enumerate the ApiFunctionSchema columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
            Id,
            [EnumTextValue("SeqNum")]
            [ColumnEnum("SeqNum", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
            SeqNum,
            [EnumTextValue("FunctionID")]
            [ColumnEnum("FunctionID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
            FunctionId,
            [EnumTextValue("TravFieldName")]
            [ColumnEnum("TravFieldName", typeof(System.String), System.Data.DbType.String, false, false, true, 128)]
            TravFieldName,
            [EnumTextValue("ApiFieldName")]
            [ColumnEnum("ApiFieldName", typeof(System.String), System.Data.DbType.String, false, false, true, 128)]
            ApiFieldName,
            [EnumTextValue("ValueTranslation")]
            [ColumnEnum("ValueTranslation", typeof(System.String), System.Data.DbType.String, false, false, true)]
            ValueTranslation,
            [EnumTextValue("Notes")]
            [ColumnEnum("Notes", typeof(System.String), System.Data.DbType.String, false, false, true)]
            Notes,
            [EnumTextValue("FieldSetting")]
            [ColumnEnum("FieldSetting", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            FieldSetting,
            [EnumTextValue("ChildFunctionID")]
            [ColumnEnum("ChildFunctionID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
            ChildFunctionId,
            [EnumTextValue("QueryColumnName")]
            [ColumnEnum("QueryColumnName", typeof(System.String), System.Data.DbType.String, false, false, true, 128)]
            QueryColumnName,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts
        }//End enum

        #endregion ApiFunctionSchemaColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("TravFieldName", 128));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("ApiFieldName", 128));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("QueryColumnName", 128));
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiFunctionSchemaEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiFunctionSchemaEntityData;
            }
        }
        #endregion

    }
}

