//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Wednesday, January 29, 2020
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiFunctionSchema' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiFunctionSchemaEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiFunctionSchema"</remarks>
        public System.Int64 Id;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// SeqNum : 
        /// </summary>
        public System.Int32? SeqNum = null;

        /// <summary>
        /// FunctionID : 
        /// </summary>
        public System.Guid? FunctionId = null;

        /// <summary>
        /// TravFieldName : 
        /// </summary>
        public System.String TravFieldName = null;

        /// <summary>
        /// ApiFieldName : 
        /// </summary>
        public System.String ApiFieldName = null;

        /// <summary>
        /// ValueTranslation : 
        /// </summary>
        public System.String ValueTranslation = null;

        /// <summary>
        /// Notes : 
        /// </summary>
        public System.String Notes = null;

        /// <summary>
        /// FieldSetting : 
        /// </summary>
        public System.Byte? FieldSetting = null;

        /// <summary>
        /// ChildFunctionID : 
        /// </summary>
        public System.Guid? ChildFunctionId = null;

        /// <summary>
        /// QueryColumnName : 
        /// </summary>
        public System.String QueryColumnName = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiFunctionSchemaEntityData _tmp = new ApiFunctionSchemaEntityData();

            _tmp.Id = this.Id;

            _tmp.SeqNum = this.SeqNum;
            _tmp.FunctionId = this.FunctionId;
            _tmp.TravFieldName = this.TravFieldName;
            _tmp.ApiFieldName = this.ApiFieldName;
            _tmp.ValueTranslation = this.ValueTranslation;
            _tmp.Notes = this.Notes;
            _tmp.FieldSetting = this.FieldSetting;
            _tmp.ChildFunctionId = this.ChildFunctionId;
            _tmp.QueryColumnName = this.QueryColumnName;
            _tmp.Ts = this.Ts;

            return _tmp;
        }

    }//End struct
}


