//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiUserFunctionAccess.
    /// </summary>
    public sealed class ApiUserFunctionAccessDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiUserFunctionAccess_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiUserFunctionAccess_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@UserFunctionId", keyValues["UserFunctionID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionAccessBase oEntity = entity as ApiUserFunctionAccessBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionAccess_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, oEntity.UserFunctionId);
            database.AddInParameter(commandWrapper, "@OriginalUserFunctionId", DbType.Int64, oEntity.OriginalUserFunctionId);
            database.AddInParameter(commandWrapper, "@AccessCount", DbType.Int64, (oEntity.AccessCount.HasValue ? (object)oEntity.AccessCount : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FirstAccessTime", DbType.DateTime, (oEntity.FirstAccessTime.HasValue ? (object)oEntity.FirstAccessTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@LastAccessTime", DbType.DateTime, (oEntity.LastAccessTime.HasValue ? (object)oEntity.LastAccessTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@LastAccessMethod", DbType.Byte, (oEntity.LastAccessMethod.HasValue ? (object)oEntity.LastAccessMethod : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");
            oEntity.OriginalUserFunctionId = oEntity.UserFunctionId;

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionAccessBase oEntity = entity as ApiUserFunctionAccessBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionAccess_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, oEntity.UserFunctionId);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                throw new DBConcurrencyException("The record has been modified by an other user. Please reload the instance before deleting.");
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserFunctionAccessBase oEntity = entity as ApiUserFunctionAccessBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserFunctionAccess_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@UserFunctionId", DbType.Int64, oEntity.UserFunctionId);
            database.AddInParameter(commandWrapper, "@AccessCount", DbType.Int64, (oEntity.AccessCount.HasValue ? (object)oEntity.AccessCount : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@FirstAccessTime", DbType.DateTime, (oEntity.FirstAccessTime.HasValue ? (object)oEntity.FirstAccessTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@LastAccessTime", DbType.DateTime, (oEntity.LastAccessTime.HasValue ? (object)oEntity.LastAccessTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@LastAccessMethod", DbType.Byte, (oEntity.LastAccessMethod.HasValue ? (object)oEntity.LastAccessMethod : System.DBNull.Value));
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@Ts");
            oEntity.OriginalUserFunctionId = oEntity.UserFunctionId;
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiUserFunctionAccess";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("UserFunctionID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("AccessCount", typeof(System.Int64));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("FirstAccessTime", typeof(System.DateTime));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("LastAccessTime", typeof(System.DateTime));
            col3.AllowDBNull = true;
            DataColumn col4 = dataTable.Columns.Add("LastAccessMethod", typeof(System.Byte));
            col4.AllowDBNull = true;
            DataColumn col5 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col5.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("UserFunctionID", "UserFunctionID");
            bulkCopy.ColumnMappings.Add("AccessCount", "AccessCount");
            bulkCopy.ColumnMappings.Add("FirstAccessTime", "FirstAccessTime");
            bulkCopy.ColumnMappings.Add("LastAccessTime", "LastAccessTime");
            bulkCopy.ColumnMappings.Add("LastAccessMethod", "LastAccessMethod");
            bulkCopy.ColumnMappings.Add("ts", "ts");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiUserFunctionAccessBase entity = list.Current as ApiUserFunctionAccessBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["UserFunctionID"] = entity.UserFunctionId;
                row["AccessCount"] = entity.AccessCount.HasValue ? (object)entity.AccessCount : System.DBNull.Value;
                row["FirstAccessTime"] = entity.FirstAccessTime.HasValue ? (object)entity.FirstAccessTime : System.DBNull.Value;
                row["LastAccessTime"] = entity.LastAccessTime.HasValue ? (object)entity.LastAccessTime : System.DBNull.Value;
                row["LastAccessMethod"] = entity.LastAccessMethod.HasValue ? (object)entity.LastAccessMethod : System.DBNull.Value;
                row["ts"] = entity.Ts;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

