//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraverseApiInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraverseApiInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;appSettings&gt;
        ///    &lt;!-- Traverse System Options --&gt;
        ///	&lt;!-- Change these options to your liking --&gt;
        ///	&lt;add key=&quot;EnableAuditLogProcess&quot; value=&quot;True&quot; /&gt;
        ///  &lt;add key=&quot;ApiUserPortalTitle&quot; value=&quot;Traverse API&quot;/&gt;
        ///	&lt;!-- Traverse Connection Settings--&gt;
        ///	&lt;!-- It is not recommended to edit this file outside of the API installer --&gt;
        ///	&lt;add key=&quot;TravLicenseServer&quot; value=&quot;{0}&quot; /&gt;
        ///	&lt;add key=&quot;TravLicensePort&quot; value=&quot;{1}&quot; /&gt;
        ///	&lt;add key=&quot;TraverseSysDB&quot; value=&quot;{4}&quot; /&gt;
        ///  &lt;add key=&quot;DfltCompanyDB&quot; value=&quot;{5}&quot; /&gt;
        ///  &lt;add key= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiConnectionFile {
            get {
                return ResourceManager.GetString("ApiConnectionFile", resourceCulture);
            }
        }
    }
}
