//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
#region using directives
using System;
using TRAVERSE.Core;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUser'.
    ///</summary>
    [Serializable]
    public partial class ApiUser : ApiUserBase
    {
        #region Constructors
        /// <summary>
        /// This constructor is used for serialization purpose only.
        /// </summary>
        public ApiUser() : base(null) { }
        /// <summary>
        /// Use this constructor by default.
        /// </summary>
        public ApiUser(string compId)
            : base(compId)
        {
            Id = IdGen.GetLongId(null);
            DateModified = DateCreated = DateTime.Now;
        }
        #endregion Constructors
    }
}
