//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Thursday, February 20, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiInfoProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiInfoProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiInfoProviderBase<T> : EntityProviderBase<T>
        where T : ApiInfoBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiInfoDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.Id = (System.Int32)reader["ID"];
                    c.OriginalId = c.Id;
                    c.SysDb = (reader.IsDBNull(reader.GetOrdinal("SysDb"))) ? null : (System.String)reader["SysDb"];
                    c.Version = (reader.IsDBNull(reader.GetOrdinal("Version"))) ? null : (System.String)reader["Version"];
                    c.AuthorizeTimeout = (reader.IsDBNull(reader.GetOrdinal("AuthorizeTimeout"))) ? null : (System.Int32?)reader["AuthorizeTimeout"];
                    c.AccessExpireHours = (reader.IsDBNull(reader.GetOrdinal("AccessExpireHours"))) ? null : (System.Int32?)reader["AccessExpireHours"];
                    c.RefreshExpireDays = (reader.IsDBNull(reader.GetOrdinal("RefreshExpireDays"))) ? null : (System.Int32?)reader["RefreshExpireDays"];
                    c.IsDebugLocalEnv = (reader.IsDBNull(reader.GetOrdinal("IsDebugLocalEnv"))) ? null : (System.Boolean?)reader["IsDebugLocalEnv"];
                    c.IgnoreInvalidField = (reader.IsDBNull(reader.GetOrdinal("IgnoreInvalidField"))) ? null : (System.Boolean?)reader["IgnoreInvalidField"];
                    c.UseMsgSecurity = (reader.IsDBNull(reader.GetOrdinal("UseMsgSecurity"))) ? null : (System.Boolean?)reader["UseMsgSecurity"];
                    c.MsgSharedKey = (reader.IsDBNull(reader.GetOrdinal("MsgSharedKey"))) ? null : (System.String)reader["MsgSharedKey"];
                    c.MsgEncryption = (reader.IsDBNull(reader.GetOrdinal("MsgEncryption"))) ? null : (System.Byte?)reader["MsgEncryption"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts"))) ? null : (System.Byte[])reader["ts"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
