//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
#region using directives
using System;
using System.Collections.Generic;
using TRAVERSE.Core;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiFunctionHeader'.
    ///</summary>
    [Serializable]
    public partial class ApiFunctionHeaderProvider : ApiFunctionHeaderProviderBase<ApiFunctionHeader>
    {
    }
}
