//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiFunctionHeader.cs

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
using TRAVERSE.Core;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiFunctionHeader'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiFunctionHeaderBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiFunctionHeaderEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiFunctionHeaderEntityData backupData;
        
        #endregion
        
        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiFunctionHeaderBase(string compId):base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiFunctionHeaderEntityData();
            this.backupData = null;
        }
        #endregion
        
        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is uniqueidentifier.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, false, false)]
        public virtual System.Guid Id
        {
            get
            {
                return this.entityData.Id; 
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;
                    
                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }
        
        /// <summary>
        ///Get the original value of the ID property.
        /// </summary>
        /// <remarks>This is the original value of the ID property.</remarks>
        /// <value>This type is uniqueidentifier</value>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public  virtual System.Guid OriginalId
        {
            get { return this.entityData.OriginalId; }
            set { this.entityData.OriginalId = value; }
        }
        
        /// <summary>
        /// Gets or sets the database field Name. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 50)]
        public virtual System.String Name
        {
            get
            {
                return this.entityData.Name; 
            }
            set
            {
                if (this.entityData.Name == value)
                    return;
                    
                OnColumnChanging("Name");
                this.entityData.Name = value;
                OnColumnChanged("Name");
                OnPropertyChanged("Name");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field AppId. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 4)]
        public virtual System.String AppId
        {
            get
            {
                return this.entityData.AppId; 
            }
            set
            {
                if (this.entityData.AppId == value)
                    return;
                    
                OnColumnChanging("AppId");
                this.entityData.AppId = value;
                OnColumnChanged("AppId");
                OnPropertyChanged("AppId");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field Type. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? Type
        {
            get
            {
                return this.entityData.Type; 
            }
            set
            {
                if (this.entityData.Type == value && this.entityData.Type != null )
                    return;
                    
                OnColumnChanging("Type");
                this.entityData.Type = value;
                OnColumnChanged("Type");
                OnPropertyChanged("Type");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field Notes. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String Notes
        {
            get
            {
                return this.entityData.Notes; 
            }
            set
            {
                if (this.entityData.Notes == value)
                    return;
                    
                OnColumnChanging("Notes");
                this.entityData.Notes = value;
                OnColumnChanged("Notes");
                OnPropertyChanged("Notes");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field Scope. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? Scope
        {
            get
            {
                return this.entityData.Scope; 
            }
            set
            {
                if (this.entityData.Scope == value && this.entityData.Scope != null )
                    return;
                    
                OnColumnChanging("Scope");
                this.entityData.Scope = value;
                OnColumnChanged("Scope");
                OnPropertyChanged("Scope");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field OverrideID. 
        /// </summary>
        /// <value>This type is uniqueidentifier.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Guid? OverrideId
        {
            get
            {
                return this.entityData.OverrideId; 
            }
            set
            {
                if (this.entityData.OverrideId == value && this.entityData.OverrideId != null )
                    return;
                    
                OnColumnChanging("OverrideId");
                this.entityData.OverrideId = value;
                OnColumnChanged("OverrideId");
                OnPropertyChanged("OverrideId");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field QueryTableName. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String QueryTableName
        {
            get
            {
                return this.entityData.QueryTableName; 
            }
            set
            {
                if (this.entityData.QueryTableName == value)
                    return;
                    
                OnColumnChanging("QueryTableName");
                this.entityData.QueryTableName = value;
                OnColumnChanged("QueryTableName");
                OnPropertyChanged("QueryTableName");
            }
        }
        
        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts; 
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;
                    
                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }
        
        #endregion "Properties"
        
        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiFunctionHeader"; }
        }
        
        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] {"ID", "Name", "AppId", "Type", "Notes", "Scope", "OverrideID", "QueryTableName", "ts"};
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] {"ID"}; }
        }
        #region ApiFunctionHeaderColumn Enum
        
        /// <summary>
        /// Enumerate the ApiFunctionHeader columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
            Id,
            [EnumTextValue("Name")]
            [ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
            Name,
            [EnumTextValue("AppId")]
            [ColumnEnum("AppId", typeof(System.String), System.Data.DbType.String, false, false, true, 4)]
            AppId,
            [EnumTextValue("Type")]
            [ColumnEnum("Type", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            Type,
            [EnumTextValue("Notes")]
            [ColumnEnum("Notes", typeof(System.String), System.Data.DbType.String, false, false, true)]
            Notes,
            [EnumTextValue("Scope")]
            [ColumnEnum("Scope", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            Scope,
            [EnumTextValue("OverrideID")]
            [ColumnEnum("OverrideID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
            OverrideId,
            [EnumTextValue("QueryTableName")]
            [ColumnEnum("QueryTableName", typeof(System.String), System.Data.DbType.String, false, false, true)]
            QueryTableName,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts
        }//End enum
    
        #endregion ApiFunctionHeaderColumn Enum        
        #endregion     
        #region Validation
        
        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength,new CommonRules.MaxLengthRuleArgs("Name",50));
            ValidationRules.AddRule(CommonRules.StringMaxLength,new CommonRules.MaxLengthRuleArgs("AppId",4));
        }
           #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiFunctionHeaderEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiFunctionHeaderEntityData;
            }
        }
        #endregion

    }
}    

