//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
#region Using directives
using System;
using System.ComponentModel;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///The data structure representation of the 'ApiUser' table.
    ///</summary>
    ///<remarks>
    ///This struct is generated by a tool and should never be modified.
    ///</remarks>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Serializable]
    internal class ApiUserEntityData : ICloneable
    {
        #region Variable Declarations

        #region Primary key(s)
        /// <summary>			
        /// ID : 
        /// </summary>
        /// <remarks>Member of the primary key of the underlying table "ApiUser"</remarks>
        public System.Int64 Id;

        /// <summary>
        /// keep a copy of the original so it can be used for editable primary keys.
        /// </summary>
        public System.Int64 OriginalId;

        #endregion

        #region Non Primary key(s)


        /// <summary>
        /// EmailAddress : 
        /// </summary>
        public System.String EmailAddress = null;

        /// <summary>
        /// Password : 
        /// </summary>
        public System.String Password = null;

        /// <summary>
        /// Name : 
        /// </summary>
        public System.String Name = null;

        /// <summary>
        /// Role : 
        /// </summary>
        public System.Byte? Role = null;

        /// <summary>
        /// Status : 
        /// </summary>
        public System.Byte? Status = null;

        /// <summary>
        /// ResetPassword : 
        /// </summary>
        public System.Boolean? ResetPassword = null;

        /// <summary>
        /// AdditionalInfo : 
        /// </summary>
        public System.String AdditionalInfo = null;

        /// <summary>
        /// ExpirationDate : 
        /// </summary>
        public System.DateTime? ExpirationDate = null;

        /// <summary>
        /// ClientID : 
        /// </summary>
        public System.Guid? ClientId = null;

        /// <summary>
        /// ClientSecret : 
        /// </summary>
        public System.String ClientSecret = null;

        /// <summary>
        /// DateCreated : 
        /// </summary>
        public System.DateTime? DateCreated = null;

        /// <summary>
        /// DateModified : 
        /// </summary>
        public System.DateTime? DateModified = null;

        /// <summary>
        /// ModifiedBy : 
        /// </summary>
        public System.String ModifiedBy = null;

        /// <summary>
        /// ts : 
        /// </summary>
        public System.Byte[] Ts = null;
        #endregion

        #endregion "Variable Declarations"

        public Object Clone()
        {
            ApiUserEntityData _tmp = new ApiUserEntityData();

            _tmp.Id = this.Id;
            _tmp.OriginalId = this.OriginalId;

            _tmp.EmailAddress = this.EmailAddress;
            _tmp.Password = this.Password;
            _tmp.Name = this.Name;
            _tmp.Role = this.Role;
            _tmp.Status = this.Status;
            _tmp.ResetPassword = this.ResetPassword;
            _tmp.AdditionalInfo = this.AdditionalInfo;
            _tmp.ExpirationDate = this.ExpirationDate;
            _tmp.ClientId = this.ClientId;
            _tmp.ClientSecret = this.ClientSecret;
            _tmp.DateCreated = this.DateCreated;
            _tmp.DateModified = this.DateModified;
            _tmp.ModifiedBy = this.ModifiedBy;
            _tmp.Ts = this.Ts;

            return _tmp;
        }

    }//End struct
}


