//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiUser'.
    ///</summary>
    [Serializable]
    public partial class ApiUserProvider : ApiUserProviderBase<ApiUser>
    {
    }
}
