//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUser.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
using TRAVERSE.Business.Validation;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUser'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiUserBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiUserEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiUserEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiUserBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiUserEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field ID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, false, false)]
        public virtual System.Int64 Id
        {
            get
            {
                return this.entityData.Id;
            }
            set
            {
                if (!this.IsNew || this.entityData.Id == value)
                    return;

                OnColumnChanging("Id");
                this.entityData.Id = value;
                OnColumnChanged("Id");
                OnPropertyChanged("Id");
            }
        }

        /// <summary>
        ///Get the original value of the ID property.
        /// </summary>
        /// <remarks>This is the original value of the ID property.</remarks>
        /// <value>This type is bigint</value>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public virtual System.Int64 OriginalId
        {
            get { return this.entityData.OriginalId; }
            set { this.entityData.OriginalId = value; }
        }

        /// <summary>
        /// Gets or sets the database field EmailAddress. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 256)]
        public virtual System.String EmailAddress
        {
            get
            {
                return this.entityData.EmailAddress;
            }
            set
            {
                if (this.entityData.EmailAddress == value)
                    return;

                OnColumnChanging("EmailAddress");
                this.entityData.EmailAddress = value;
                OnColumnChanged("EmailAddress");
                OnPropertyChanged("EmailAddress");
            }
        }

        /// <summary>
        /// Gets or sets the database field Password. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 256)]
        public virtual System.String Password
        {
            get
            {
                return this.entityData.Password;
            }
            set
            {
                if (this.entityData.Password == value)
                    return;

                OnColumnChanging("Password");
                this.entityData.Password = value;
                OnColumnChanged("Password");
                OnPropertyChanged("Password");
            }
        }

        /// <summary>
        /// Gets or sets the database field Name. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 200)]
        public virtual System.String Name
        {
            get
            {
                return this.entityData.Name;
            }
            set
            {
                if (this.entityData.Name == value)
                    return;

                OnColumnChanging("Name");
                this.entityData.Name = value;
                OnColumnChanged("Name");
                OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Gets or sets the database field Role. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? Role
        {
            get
            {
                return this.entityData.Role;
            }
            set
            {
                if (this.entityData.Role == value && this.entityData.Role != null)
                    return;

                OnColumnChanging("Role");
                this.entityData.Role = value;
                OnColumnChanged("Role");
                OnPropertyChanged("Role");
            }
        }

        /// <summary>
        /// Gets or sets the database field Status. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? Status
        {
            get
            {
                return this.entityData.Status;
            }
            set
            {
                if (this.entityData.Status == value && this.entityData.Status != null)
                    return;

                OnColumnChanging("Status");
                this.entityData.Status = value;
                OnColumnChanged("Status");
                OnPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Gets or sets the database field ResetPassword. 
        /// </summary>
        /// <value>This type is bit.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Boolean? ResetPassword
        {
            get
            {
                return this.entityData.ResetPassword;
            }
            set
            {
                if (this.entityData.ResetPassword == value && this.entityData.ResetPassword != null)
                    return;

                OnColumnChanging("ResetPassword");
                this.entityData.ResetPassword = value;
                OnColumnChanged("ResetPassword");
                OnPropertyChanged("ResetPassword");
            }
        }

        /// <summary>
        /// Gets or sets the database field AdditionalInfo. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String AdditionalInfo
        {
            get
            {
                return this.entityData.AdditionalInfo;
            }
            set
            {
                if (this.entityData.AdditionalInfo == value)
                    return;

                OnColumnChanging("AdditionalInfo");
                this.entityData.AdditionalInfo = value;
                OnColumnChanged("AdditionalInfo");
                OnPropertyChanged("AdditionalInfo");
            }
        }

        /// <summary>
        /// Gets or sets the database field ExpirationDate. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? ExpirationDate
        {
            get
            {
                return this.entityData.ExpirationDate;
            }
            set
            {
                if (this.entityData.ExpirationDate == value && this.entityData.ExpirationDate != null)
                    return;

                OnColumnChanging("ExpirationDate");
                this.entityData.ExpirationDate = value;
                OnColumnChanged("ExpirationDate");
                OnPropertyChanged("ExpirationDate");
            }
        }

        /// <summary>
        /// Gets or sets the database field ClientID. 
        /// </summary>
        /// <value>This type is uniqueidentifier.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Guid? ClientId
        {
            get
            {
                return this.entityData.ClientId;
            }
            set
            {
                if (this.entityData.ClientId == value && this.entityData.ClientId != null)
                    return;

                OnColumnChanging("ClientId");
                this.entityData.ClientId = value;
                OnColumnChanged("ClientId");
                OnPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// Gets or sets the database field ClientSecret. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.String ClientSecret
        {
            get
            {
                return this.entityData.ClientSecret;
            }
            set
            {
                if (this.entityData.ClientSecret == value)
                    return;

                OnColumnChanging("ClientSecret");
                this.entityData.ClientSecret = value;
                OnColumnChanged("ClientSecret");
                OnPropertyChanged("ClientSecret");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateCreated. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateCreated
        {
            get
            {
                return this.entityData.DateCreated;
            }
            set
            {
                if (this.entityData.DateCreated == value && this.entityData.DateCreated != null)
                    return;

                OnColumnChanging("DateCreated");
                this.entityData.DateCreated = value;
                OnColumnChanged("DateCreated");
                OnPropertyChanged("DateCreated");
            }
        }

        /// <summary>
        /// Gets or sets the database field DateModified. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? DateModified
        {
            get
            {
                return this.entityData.DateModified;
            }
            set
            {
                if (this.entityData.DateModified == value && this.entityData.DateModified != null)
                    return;

                OnColumnChanging("DateModified");
                this.entityData.DateModified = value;
                OnColumnChanged("DateModified");
                OnPropertyChanged("DateModified");
            }
        }

        /// <summary>
        /// Gets or sets the database field ModifiedBy. 
        /// </summary>
        /// <value>This type is nvarchar.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true, 100)]
        public virtual System.String ModifiedBy
        {
            get
            {
                return this.entityData.ModifiedBy;
            }
            set
            {
                if (this.entityData.ModifiedBy == value)
                    return;

                OnColumnChanging("ModifiedBy");
                this.entityData.ModifiedBy = value;
                OnColumnChanged("ModifiedBy");
                OnPropertyChanged("ModifiedBy");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiUser"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "ID", "EmailAddress", "Password", "Name", "Role", "Status", "ResetPassword", "AdditionalInfo", "ExpirationDate", "ClientID", "ClientSecret", "DateCreated", "DateModified", "ModifiedBy", "ts" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "ID" }; }
        }
        #region ApiUserColumn Enum

        /// <summary>
        /// Enumerate the ApiUser columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("ID")]
            [ColumnEnum("ID", typeof(System.Int64), System.Data.DbType.Int64, true, false, false)]
            Id,
            [EnumTextValue("EmailAddress")]
            [ColumnEnum("EmailAddress", typeof(System.String), System.Data.DbType.String, false, false, true, 256)]
            EmailAddress,
            [EnumTextValue("Password")]
            [ColumnEnum("Password", typeof(System.String), System.Data.DbType.String, false, false, true, 256)]
            Password,
            [EnumTextValue("Name")]
            [ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
            Name,
            [EnumTextValue("Role")]
            [ColumnEnum("Role", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            Role,
            [EnumTextValue("Status")]
            [ColumnEnum("Status", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            Status,
            [EnumTextValue("ResetPassword")]
            [ColumnEnum("ResetPassword", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
            ResetPassword,
            [EnumTextValue("AdditionalInfo")]
            [ColumnEnum("AdditionalInfo", typeof(System.String), System.Data.DbType.String, false, false, true)]
            AdditionalInfo,
            [EnumTextValue("ExpirationDate")]
            [ColumnEnum("ExpirationDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            ExpirationDate,
            [EnumTextValue("ClientID")]
            [ColumnEnum("ClientID", typeof(System.Guid), System.Data.DbType.Guid, false, false, true)]
            ClientId,
            [EnumTextValue("ClientSecret")]
            [ColumnEnum("ClientSecret", typeof(System.String), System.Data.DbType.String, false, false, true)]
            ClientSecret,
            [EnumTextValue("DateCreated")]
            [ColumnEnum("DateCreated", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateCreated,
            [EnumTextValue("DateModified")]
            [ColumnEnum("DateModified", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            DateModified,
            [EnumTextValue("ModifiedBy")]
            [ColumnEnum("ModifiedBy", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
            ModifiedBy,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts
        }//End enum

        #endregion ApiUserColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("EmailAddress", 256));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("Password", 256));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("Name", 200));
            ValidationRules.AddRule(CommonRules.StringMaxLength, new CommonRules.MaxLengthRuleArgs("ModifiedBy", 100));
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiUserEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiUserEntityData;
            }
        }
        #endregion

    }
}

