//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserProvider.cs
#region Using directives
using System;
using System.Data;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    /// <summary>
    /// Base class for ApiUserProvider.
    /// </summary>
    [Serializable]
    public abstract class ApiUserProviderBase<T> : EntityProviderBase<T>
        where T : ApiUserBase, new()
    {
        private static IDataProvider _dataProvider = null;

        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("OSI.TraverseApi.Data", "ApiUserDataProvider");
        }
        #endregion "Helper"

        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }

            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done

                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);

                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.Id = (System.Int64)reader["ID"];
                    c.OriginalId = c.Id;
                    c.EmailAddress = (reader.IsDBNull(reader.GetOrdinal("EmailAddress"))) ? null : (System.String)reader["EmailAddress"];
                    c.Password = (reader.IsDBNull(reader.GetOrdinal("Password"))) ? null : (System.String)reader["Password"];
                    c.Name = (reader.IsDBNull(reader.GetOrdinal("Name"))) ? null : (System.String)reader["Name"];
                    c.Role = (reader.IsDBNull(reader.GetOrdinal("Role"))) ? null : (System.Byte?)reader["Role"];
                    c.Status = (reader.IsDBNull(reader.GetOrdinal("Status"))) ? null : (System.Byte?)reader["Status"];
                    c.ResetPassword = (reader.IsDBNull(reader.GetOrdinal("ResetPassword"))) ? null : (System.Boolean?)reader["ResetPassword"];
                    c.AdditionalInfo = (reader.IsDBNull(reader.GetOrdinal("AdditionalInfo"))) ? null : (System.String)reader["AdditionalInfo"];
                    c.ExpirationDate = (reader.IsDBNull(reader.GetOrdinal("ExpirationDate"))) ? null : (System.DateTime?)reader["ExpirationDate"];
                    c.ClientId = (reader.IsDBNull(reader.GetOrdinal("ClientID"))) ? null : (System.Guid?)reader["ClientID"];
                    c.ClientSecret = (reader.IsDBNull(reader.GetOrdinal("ClientSecret"))) ? null : (System.String)reader["ClientSecret"];
                    c.DateCreated = (reader.IsDBNull(reader.GetOrdinal("DateCreated"))) ? null : (System.DateTime?)reader["DateCreated"];
                    c.DateModified = (reader.IsDBNull(reader.GetOrdinal("DateModified"))) ? null : (System.DateTime?)reader["DateModified"];
                    c.ModifiedBy = (reader.IsDBNull(reader.GetOrdinal("ModifiedBy"))) ? null : (System.String)reader["ModifiedBy"];
                    c.Ts = (reader.IsDBNull(reader.GetOrdinal("ts"))) ? null : (System.Byte[])reader["ts"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
