//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************
#region using directives
using System;
#endregion
namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///Entity provider for ApiUserFunctionAccess'.
    ///</summary>
    [Serializable]
    internal partial class ApiUserFunctionAccessProvider : ApiUserFunctionAccessProviderBase<ApiUserFunctionAccess>
    {
    }
}
