//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Friday, January 24, 2020
//**************************************
//DO NOT edit this file. Instead use the partial class in ApiUserFunctionAccess.cs

#region using directives
using System;
using System.ComponentModel;
using System.Xml.Serialization;
using TRAVERSE.Business;
#endregion

namespace OSI.TraverseApi.Business
{
    ///<summary>
    ///An object representation of 'ApiUserFunctionAccess'.
    ///</summary>
    [Serializable, DataObject]
    public abstract class ApiUserFunctionAccessBase : EntityBase
    {
        #region Fields
        ///<summary>
        ///inner data of the entity.
        ///</summary>
        private ApiUserFunctionAccessEntityData entityData;

        ///<summary>
        ///a backup of the inner data of the entity.
        ///</summary>
        private ApiUserFunctionAccessEntityData backupData;

        #endregion

        #region Constructor
        /// <summary>
        /// Instantiates the object and initializes inner data classes.
        /// </summary>
        protected ApiUserFunctionAccessBase(string compId) : base(compId)
        {
            //initialize inner dataclass
            this.entityData = new ApiUserFunctionAccessEntityData();
            this.backupData = null;
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets the database field UserFunctionID. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can not be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(true, false, false)]
        public virtual System.Int64 UserFunctionId
        {
            get
            {
                return this.entityData.UserFunctionId;
            }
            set
            {
                if (!this.IsNew || this.entityData.UserFunctionId == value)
                    return;

                OnColumnChanging("UserFunctionId");
                this.entityData.UserFunctionId = value;
                OnColumnChanged("UserFunctionId");
                OnPropertyChanged("UserFunctionId");
            }
        }

        /// <summary>
        ///Get the original value of the UserFunctionID property.
        /// </summary>
        /// <remarks>This is the original value of the UserFunctionID property.</remarks>
        /// <value>This type is bigint</value>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public virtual System.Int64 OriginalUserFunctionId
        {
            get { return this.entityData.OriginalUserFunctionId; }
            set { this.entityData.OriginalUserFunctionId = value; }
        }

        /// <summary>
        /// Gets or sets the database field AccessCount. 
        /// </summary>
        /// <value>This type is bigint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Int64? AccessCount
        {
            get
            {
                return this.entityData.AccessCount;
            }
            set
            {
                if (this.entityData.AccessCount == value && this.entityData.AccessCount != null)
                    return;

                OnColumnChanging("AccessCount");
                this.entityData.AccessCount = value;
                OnColumnChanged("AccessCount");
                OnPropertyChanged("AccessCount");
            }
        }

        /// <summary>
        /// Gets or sets the database field FirstAccessTime. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? FirstAccessTime
        {
            get
            {
                return this.entityData.FirstAccessTime;
            }
            set
            {
                if (this.entityData.FirstAccessTime == value && this.entityData.FirstAccessTime != null)
                    return;

                OnColumnChanging("FirstAccessTime");
                this.entityData.FirstAccessTime = value;
                OnColumnChanged("FirstAccessTime");
                OnPropertyChanged("FirstAccessTime");
            }
        }

        /// <summary>
        /// Gets or sets the database field LastAccessTime. 
        /// </summary>
        /// <value>This type is datetime.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.DateTime? LastAccessTime
        {
            get
            {
                return this.entityData.LastAccessTime;
            }
            set
            {
                if (this.entityData.LastAccessTime == value && this.entityData.LastAccessTime != null)
                    return;

                OnColumnChanging("LastAccessTime");
                this.entityData.LastAccessTime = value;
                OnColumnChanged("LastAccessTime");
                OnPropertyChanged("LastAccessTime");
            }
        }

        /// <summary>
        /// Gets or sets the database field LastAccessMethod. 
        /// </summary>
        /// <value>This type is tinyint.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// It is up to the developer to check whether a null value is valid.
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(true)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte? LastAccessMethod
        {
            get
            {
                return this.entityData.LastAccessMethod;
            }
            set
            {
                if (this.entityData.LastAccessMethod == value && this.entityData.LastAccessMethod != null)
                    return;

                OnColumnChanging("LastAccessMethod");
                this.entityData.LastAccessMethod = value;
                OnColumnChanged("LastAccessMethod");
                OnPropertyChanged("LastAccessMethod");
            }
        }

        /// <summary>
        /// Gets or sets the database field ts. 
        /// </summary>
        /// <value>This type is timestamp.</value>
        /// <remarks>
        /// This property can be set to null. 
        /// </remarks>
        [DescriptionAttribute(""), BindableAttribute(false)]
        [DataObjectField(false, false, true)]
        public virtual System.Byte[] Ts
        {
            get
            {
                return this.entityData.Ts;
            }
            set
            {
                if (this.entityData.Ts == value)
                    return;

                OnColumnChanging("Ts");
                this.entityData.Ts = value;
                OnColumnChanged("Ts");
                OnPropertyChanged("Ts");
            }
        }

        #endregion "Properties"

        #region Table Meta Data
        /// <summary>
        ///The name of the underlying database table.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string TableName
        {
            get { return "ApiUserFunctionAccess"; }
        }

        /// <summary>
        ///The name of the underlying database table's columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] TableColumns
        {
            get
            {
                return new string[] { "UserFunctionID", "AccessCount", "FirstAccessTime", "LastAccessTime", "LastAccessMethod", "ts" };
            }
        }
        /// <summary>
        /// Array containing name of primary key columns.
        /// </summary>
        [BrowsableAttribute(false), XmlIgnoreAttribute()]
        public static string[] KeyColumns
        {
            get { return new string[] { "UserFunctionID" }; }
        }
        #region ApiUserFunctionAccessColumn Enum

        /// <summary>
        /// Enumerate the ApiUserFunctionAccess columns.
        /// </summary>
        [Serializable]
        public enum Columns
        {
            [EnumTextValue("UserFunctionID")]
            [ColumnEnum("UserFunctionID", typeof(System.Int64), System.Data.DbType.Int64, true, false, false)]
            UserFunctionId,
            [EnumTextValue("AccessCount")]
            [ColumnEnum("AccessCount", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
            AccessCount,
            [EnumTextValue("FirstAccessTime")]
            [ColumnEnum("FirstAccessTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            FirstAccessTime,
            [EnumTextValue("LastAccessTime")]
            [ColumnEnum("LastAccessTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
            LastAccessTime,
            [EnumTextValue("LastAccessMethod")]
            [ColumnEnum("LastAccessMethod", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
            LastAccessMethod,
            [EnumTextValue("ts")]
            [ColumnEnum("ts", typeof(System.Byte[]), System.Data.DbType.Binary, false, false, true)]
            Ts
        }//End enum

        #endregion ApiUserFunctionAccessColumn Enum        
        #endregion
        #region Validation

        /// <summary>
        /// Assigns validation rules to this object based on model definition.
        /// </summary>
        /// <remarks>This method overrides the base class to add schema related validation.</remarks>
        protected override void AddValidationRules()
        {
            //Validation rules based on database schema.
        }
        #endregion
        #region Overrides
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable BackupData
        {
            get
            {
                return backupData;
            }
            set
            {
                backupData = value as ApiUserFunctionAccessEntityData;
            }
        }
        /// <summary>
        /// Data structure with backing fields for entity class.
        /// </summary>
        protected override ICloneable EntityData
        {
            get
            {
                return entityData;
            }
            set
            {
                entityData = value as ApiUserFunctionAccessEntityData;
            }
        }
        #endregion

    }
}

