//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAVERSE.Web.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRAVERSE.Web.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of Loaded Assemblies.
        /// </summary>
        internal static string ApiAssemblyCount {
            get {
                return ResourceManager.GetString("ApiAssemblyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Build Number.
        /// </summary>
        internal static string ApiAssemblyVersion {
            get {
                return ResourceManager.GetString("ApiAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api:ClientId.
        /// </summary>
        internal static string ApiAuthClientId {
            get {
                return ResourceManager.GetString("ApiAuthClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiBodyContent.
        /// </summary>
        internal static string ApiBodyContent {
            get {
                return ResourceManager.GetString("ApiBodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message -.
        /// </summary>
        internal static string ApiBrokenRuleMsg {
            get {
                return ResourceManager.GetString("ApiBrokenRuleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load child object for {0}. Either the object does not exist or you do not have permission to it. If you feel this is in error, have your account administrator review your setup in the desktop application, System Manager --&gt; Api Configuration --&gt; User Accounts..
        /// </summary>
        internal static string ApiChildObjectError {
            get {
                return ResourceManager.GetString("ApiChildObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiClient.
        /// </summary>
        internal static string ApiClientFolder {
            get {
                return ResourceManager.GetString("ApiClientFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Auth-Client.
        /// </summary>
        internal static string ApiClientIdHeader {
            get {
                return ResourceManager.GetString("ApiClientIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company id is required..
        /// </summary>
        internal static string ApiCompanyRequired {
            get {
                return ResourceManager.GetString("ApiCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Traverse company to use when executing this request..
        /// </summary>
        internal static string ApiDocumentCompanyParam {
            get {
                return ResourceManager.GetString("ApiDocumentCompanyParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityList.
        /// </summary>
        internal static string ApiEntityListName {
            get {
                return ResourceManager.GetString("ApiEntityListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityItem.
        /// </summary>
        internal static string ApiEntityName {
            get {
                return ResourceManager.GetString("ApiEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more entries do not meet the validation criteria on your account. If you feel this is in error, have your account administrator review your setup in the desktop application, System Manager --&gt; Api Configuration --&gt; User Accounts..
        /// </summary>
        internal static string ApiEntityValidationError {
            get {
                return ResourceManager.GetString("ApiEntityValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiFunctionId.
        /// </summary>
        internal static string ApiFunctionDataToken {
            get {
                return ResourceManager.GetString("ApiFunctionDataToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api:IgnoreUserAccess.
        /// </summary>
        internal static string ApiIgnoreUserAccessValidation {
            get {
                return ResourceManager.GetString("ApiIgnoreUserAccessValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided credentials are invalid.
        /// </summary>
        internal static string ApiInvalidCredential {
            get {
                return ResourceManager.GetString("ApiInvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for the field &apos;{1}&apos;.
        /// </summary>
        internal static string ApiInvalidEnumValue {
            get {
                return ResourceManager.GetString("ApiInvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not exist or you do not have permission to access it.
        /// </summary>
        internal static string ApiInvalidFieldName {
            get {
                return ResourceManager.GetString("ApiInvalidFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function {0} either does not exist or permission to the function is denied..
        /// </summary>
        internal static string ApiInvalidFunction {
            get {
                return ResourceManager.GetString("ApiInvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid_grant.
        /// </summary>
        internal static string ApiInvalidGrant {
            get {
                return ResourceManager.GetString("ApiInvalidGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has failed the message security validation..
        /// </summary>
        internal static string ApiInvalidMessage {
            get {
                return ResourceManager.GetString("ApiInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid_refresh.
        /// </summary>
        internal static string ApiInvalidRefresh {
            get {
                return ResourceManager.GetString("ApiInvalidRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided SELECT statement is invalid..
        /// </summary>
        internal static string ApiInvalidSelectStmt {
            get {
                return ResourceManager.GetString("ApiInvalidSelectStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not active.
        /// </summary>
        internal static string ApiInvalidStatus {
            get {
                return ResourceManager.GetString("ApiInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID or Client Token are invalid or OAuth requirement date has been exceeded. The OAuth requirement date is {0}.
        /// </summary>
        internal static string ApiLoginFailed {
            get {
                return ResourceManager.GetString("ApiLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required in order to process this {1} request..
        /// </summary>
        internal static string ApiMissingRequiredField {
            get {
                return ResourceManager.GetString("ApiMissingRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key is your Client ID..
        /// </summary>
        internal static string ApiMsgSecClientId {
            get {
                return ResourceManager.GetString("ApiMsgSecClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the API administrator for your key..
        /// </summary>
        internal static string ApiMsgSecContact {
            get {
                return ResourceManager.GetString("ApiMsgSecContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth 2.0 security will be required beginning {0}.
        /// </summary>
        internal static string ApiOAuthReqDate {
            get {
                return ResourceManager.GetString("ApiOAuthReqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred generating documentation for this request. Please have a system administrator review the logs for more error details..
        /// </summary>
        internal static string ApiOperationSchemaIncomplete {
            get {
                return ResourceManager.GetString("ApiOperationSchemaIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access-Control-Allow-Origin.
        /// </summary>
        internal static string ApiOriginMsg {
            get {
                return ResourceManager.GetString("ApiOriginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiPlugins.
        /// </summary>
        internal static string ApiPluginFolder {
            get {
                return ResourceManager.GetString("ApiPluginFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Response-Detail.
        /// </summary>
        internal static string ApiProcessingDetail {
            get {
                return ResourceManager.GetString("ApiProcessingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyid.
        /// </summary>
        internal static string ApiRequestCompany {
            get {
                return ResourceManager.GetString("ApiRequestCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string ApiRequestPage {
            get {
                return ResourceManager.GetString("ApiRequestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_size.
        /// </summary>
        internal static string ApiRequestPageSize {
            get {
                return ResourceManager.GetString("ApiRequestPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string ApiRequestQuery {
            get {
                return ResourceManager.GetString("ApiRequestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Num-Records-Available.
        /// </summary>
        internal static string ApiResponseRecordAvail {
            get {
                return ResourceManager.GetString("ApiResponseRecordAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Num-Records-Returned.
        /// </summary>
        internal static string ApiResponseRecordCount {
            get {
                return ResourceManager.GetString("ApiResponseRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api:DisplaySecurityNotice.
        /// </summary>
        internal static string ApiSecurityNoticeSetting {
            get {
                return ResourceManager.GetString("ApiSecurityNoticeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SELECT statement must be provided in order to perform this method..
        /// </summary>
        internal static string ApiSelectBlank {
            get {
                return ResourceManager.GetString("ApiSelectBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiMsgSignature.
        /// </summary>
        internal static string ApiSignatureHeaderKey {
            get {
                return ResourceManager.GetString("ApiSignatureHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string ApiStorageCompany {
            get {
                return ResourceManager.GetString("ApiStorageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string ApiStoragePage {
            get {
                return ResourceManager.GetString("ApiStoragePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSize.
        /// </summary>
        internal static string ApiStoragePageSize {
            get {
                return ResourceManager.GetString("ApiStoragePageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string ApiStorageQuery {
            get {
                return ResourceManager.GetString("ApiStorageQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This header parameter is an encrypted version of the request. Concatenate the full URL, the request body and the key. Compute the hash using the {0} provider. Convert the hash to Base64 string and set this value. {1}.
        /// </summary>
        internal static string ApiSwaggerMsgSecurity {
            get {
                return ResourceManager.GetString("ApiSwaggerMsgSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api{0}{1}/{2}.
        /// </summary>
        internal static string ApiTemplateFormat {
            get {
                return ResourceManager.GetString("ApiTemplateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Auth-Token.
        /// </summary>
        internal static string ApiTokenHeader {
            get {
                return ResourceManager.GetString("ApiTokenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api:UserInfo.
        /// </summary>
        internal static string ApiUserInfoStorage {
            get {
                return ResourceManager.GetString("ApiUserInfoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api:UserFunctionComp.
        /// </summary>
        internal static string ApiUserRequestActionStorage {
            get {
                return ResourceManager.GetString("ApiUserRequestActionStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Date.
        /// </summary>
        internal static string ApiVersionTableAssemblyDate {
            get {
                return ResourceManager.GetString("ApiVersionTableAssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string ApiVersionTableAssemblyName {
            get {
                return ResourceManager.GetString("ApiVersionTableAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Version.
        /// </summary>
        internal static string ApiVersionTableAssemblyVersion {
            get {
                return ResourceManager.GetString("ApiVersionTableAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray.
        /// </summary>
        internal static string ApiVersionTableEvenRowColor {
            get {
                return ResourceManager.GetString("ApiVersionTableEvenRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string ApiVersionTableOddRowColor {
            get {
                return ResourceManager.GetString("ApiVersionTableOddRowColor", resourceCulture);
            }
        }
    }
}
