//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2020, Open Systems, Inc.
//Tuesday, December 8, 2020
//**************************************
	
#region Using directives
using System;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using System.Collections;
using Microsoft.Practices.EnterpriseLibrary.Data;
using TRAVERSE.Core;
using TRAVERSE.Business;
using OSI.TraverseApi.Business;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiFunctionHeader.
    /// </summary>
    public sealed class ApiFunctionHeaderDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiFunctionHeader_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiFunctionHeader_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string,string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
			db.AddInParameter(commandWrapper, "@Id", DbType.Guid, DBNull.Value );
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@Id", keyValues["ID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }       
        #region Update Functions
                
        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiFunctionHeaderBase oEntity = entity as ApiFunctionHeaderBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");
				
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionHeader_Update", 
                UseStoredProcedure, GetCommandFromResource());
            
            database.AddInParameter(commandWrapper, "@Id", DbType.Guid, oEntity.Id );
            database.AddInParameter(commandWrapper, "@OriginalId", DbType.Guid, oEntity.OriginalId);
            database.AddInParameter(commandWrapper, "@Name", DbType.String, oEntity.Name );
            database.AddInParameter(commandWrapper, "@AppId", DbType.String, oEntity.AppId );
            database.AddInParameter(commandWrapper, "@Type", DbType.Byte, (oEntity.Type.HasValue ? (object) oEntity.Type : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes );
            database.AddInParameter(commandWrapper, "@Scope", DbType.Byte, (oEntity.Scope.HasValue ? (object) oEntity.Scope : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@OverrideId", DbType.Guid, (oEntity.OverrideId.HasValue ? (object) oEntity.OverrideId : System.DBNull.Value) );
            database.AddInParameter(commandWrapper, "@QueryTableName", DbType.String, oEntity.QueryTableName );
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts );
            database.AddOutParameter(commandWrapper, "@ReturnedTs", DbType.Binary, 8);
            
            int results = 0;
            
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            if (results == 0)
            {
                throw new DBConcurrencyException("Concurrency exception");
            }
            oEntity.Ts = (System.Byte[])database.GetParameterValue(commandWrapper, "@ReturnedTs");
            oEntity.OriginalId = oEntity.Id;
            
            oEntity.AcceptChanges();
    
            return Convert.ToBoolean(results);
        }
            
        #endregion
            
    
        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiFunctionHeaderBase oEntity = entity as ApiFunctionHeaderBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");
			
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionHeader_Delete", 
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@Id", DbType.Guid, oEntity.Id);
            database.AddInParameter(commandWrapper, "@Ts", DbType.Binary, oEntity.Ts);
            
            int results = 0;
            
            if (transaction != null)
            {	
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            
            if (results == 0)
            {
                throw new DBConcurrencyException ("The record has been modified by an other user. Please reload the instance before deleting.");
            }
            
            return Convert.ToBoolean(results);
        }//end Delete
        #endregion
    
        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction )
        {
            ApiFunctionHeaderBase oEntity = entity as ApiFunctionHeaderBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");
			
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiFunctionHeader_Insert", 
                UseStoredProcedure, GetCommandFromResource());
            
            database.AddInParameter(commandWrapper, "@Id", DbType.Guid, oEntity.Id );
            database.AddInParameter(commandWrapper, "@Name", DbType.String, oEntity.Name );
            database.AddInParameter(commandWrapper, "@AppId", DbType.String, oEntity.AppId );
            database.AddInParameter(commandWrapper, "@Type", DbType.Byte, (oEntity.Type.HasValue ? (object) oEntity.Type  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@Notes", DbType.String, oEntity.Notes );
            database.AddInParameter(commandWrapper, "@Scope", DbType.Byte, (oEntity.Scope.HasValue ? (object) oEntity.Scope  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@OverrideId", DbType.Guid, (oEntity.OverrideId.HasValue ? (object) oEntity.OverrideId  : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@QueryTableName", DbType.String, oEntity.QueryTableName );
            database.AddOutParameter(commandWrapper, "@Ts", DbType.Binary, 8);
            
            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
    
            oEntity.Ts = (System.Byte[]) database.GetParameterValue(commandWrapper, "@Ts");						
            oEntity.OriginalId = oEntity.Id;
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }	
		
        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");
			
            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }
            
            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiFunctionHeader";
            
            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("ID", typeof(System.Guid));
            col0.AllowDBNull = false;		
            DataColumn col1 = dataTable.Columns.Add("Name", typeof(System.String));
            col1.AllowDBNull = true;		
            DataColumn col2 = dataTable.Columns.Add("AppId", typeof(System.String));
            col2.AllowDBNull = true;		
            DataColumn col3 = dataTable.Columns.Add("Type", typeof(System.Byte));
            col3.AllowDBNull = true;		
            DataColumn col4 = dataTable.Columns.Add("Notes", typeof(System.String));
            col4.AllowDBNull = true;		
            DataColumn col5 = dataTable.Columns.Add("Scope", typeof(System.Byte));
            col5.AllowDBNull = true;		
            DataColumn col6 = dataTable.Columns.Add("OverrideID", typeof(System.Guid));
            col6.AllowDBNull = true;		
            DataColumn col7 = dataTable.Columns.Add("QueryTableName", typeof(System.String));
            col7.AllowDBNull = true;		
            DataColumn col8 = dataTable.Columns.Add("ts", typeof(System.Byte[]));
            col8.AllowDBNull = true;		
            
            bulkCopy.ColumnMappings.Add("ID", "ID");
            bulkCopy.ColumnMappings.Add("Name", "Name");
            bulkCopy.ColumnMappings.Add("AppId", "AppId");
            bulkCopy.ColumnMappings.Add("Type", "Type");
            bulkCopy.ColumnMappings.Add("Notes", "Notes");
            bulkCopy.ColumnMappings.Add("Scope", "Scope");
            bulkCopy.ColumnMappings.Add("OverrideID", "OverrideID");
            bulkCopy.ColumnMappings.Add("QueryTableName", "QueryTableName");
            bulkCopy.ColumnMappings.Add("ts", "ts");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiFunctionHeaderBase entity = list.Current as ApiFunctionHeaderBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                    row["ID"] = entity.Id;
                    row["Name"] = entity.Name;
                    row["AppId"] = entity.AppId;
                    row["Type"] = entity.Type.HasValue ? (object) entity.Type  : System.DBNull.Value;
                    row["Notes"] = entity.Notes;
                    row["Scope"] = entity.Scope.HasValue ? (object) entity.Scope  : System.DBNull.Value;
                    row["OverrideID"] = entity.OverrideId.HasValue ? (object) entity.OverrideId  : System.DBNull.Value;
                    row["QueryTableName"] = entity.QueryTableName;
                    row["ts"] = entity.Ts;
                
                dataTable.Rows.Add(row);
            }		
            
            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);		
            // update back the state
            list.Reset();
            while(list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }
                
        #endregion
 
        #endregion "IDataProvider"
    }
}    

