//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2019, Open Systems, Inc.
//Thursday, July 4, 2019
//**************************************

#region Using directives
using Microsoft.Practices.EnterpriseLibrary.Data;
using OSI.TraverseApi.Business;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using TRAVERSE.Business;
using TRAVERSE.Core;
#endregion

namespace TRAVERSE.Data
{
    /// <summary>
    /// Data provider class for entity ApiUserToken.
    /// </summary>
    public sealed class ApiUserTokenDataProvider : BaseProvider, IDataProvider
    {

        #region IDataProvider Members

        public IDataReader LoadData(string compId, DbTransaction transaction, FilterCriteria criteria)
        {
            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper;
            if (string.IsNullOrEmpty(criteria.WhereClause) && string.IsNullOrEmpty(criteria.OrderBy))
            {
                commandWrapper = GetListCommand("dbo.trav_ApiUserToken_GetList", database, criteria.FilterByKey);
            }
            else
            {
                commandWrapper = GetPagedCommand("dbo.trav_ApiUserToken_GetPaged", database, criteria.WhereClause, criteria.OrderBy,
                    criteria.PageSize, criteria.PageIndex);
            }

            if (transaction == null)
            {
                return database.ExecuteReader(commandWrapper);
            }
            else
            {
                return database.ExecuteReader(commandWrapper, transaction);
            }
        }

        protected override DbCommand GetListCommand(string commandName, Database db, IDictionary<string, string> keyValues)
        {
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(db, commandName,
                this.UseStoredProcedure, GetCommandFromResource());
            db.AddInParameter(commandWrapper, "@UserId", DbType.Int64, DBNull.Value);
            db.AddInParameter(commandWrapper, "@ALL", DbType.Boolean, 1);
            if (keyValues != null)
            {
                db.SetParameterValue(commandWrapper, "@UserId", keyValues["UserID"]);
                db.SetParameterValue(commandWrapper, "@ALL", 0);
            }
            return commandWrapper;
        }
        #region Update Functions

        public bool Update(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserTokenBase oEntity = entity as ApiUserTokenBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserToken_Update",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@UserId", DbType.Int64, oEntity.UserId);
            database.AddInParameter(commandWrapper, "@OriginalUserId", DbType.Int64, oEntity.OriginalUserId);
            database.AddInParameter(commandWrapper, "@RefreshToken", DbType.String, oEntity.RefreshToken);
            database.AddInParameter(commandWrapper, "@IssueTime", DbType.DateTime, (oEntity.IssueTime.HasValue ? (object)oEntity.IssueTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ExpireTime", DbType.DateTime, (oEntity.ExpireTime.HasValue ? (object)oEntity.ExpireTime : System.DBNull.Value));

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            oEntity.OriginalUserId = oEntity.UserId;

            oEntity.AcceptChanges();

            return Convert.ToBoolean(results);
        }

        #endregion


        #region Delete Functions
        public bool Delete(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserTokenBase oEntity = entity as ApiUserTokenBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserToken_Delete",
                UseStoredProcedure, GetCommandFromResource());
            database.AddInParameter(commandWrapper, "@UserId", DbType.Int64, oEntity.UserId);

            int results = 0;

            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }

            if (results == 0)
            {
                //throw new DataException("The record has been already deleted.");
                return false;
            }

            return Convert.ToBoolean(results);
        }//end Delete
        #endregion

        #region Insert Functions
        public bool Insert(string compId, IEntity entity, DbTransaction transaction)
        {
            ApiUserTokenBase oEntity = entity as ApiUserTokenBase;
            if (oEntity == null)
                throw new InvalidValueException("Unable to cast entity object");

            Database database = ConnectionSetting.GetDatabase(Core.ApplicationContext.DataConnectionString, compId);
            DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.trav_ApiUserToken_Insert",
                UseStoredProcedure, GetCommandFromResource());

            database.AddInParameter(commandWrapper, "@UserId", DbType.Int64, oEntity.UserId);
            database.AddInParameter(commandWrapper, "@RefreshToken", DbType.String, oEntity.RefreshToken);
            database.AddInParameter(commandWrapper, "@IssueTime", DbType.DateTime, (oEntity.IssueTime.HasValue ? (object)oEntity.IssueTime : System.DBNull.Value));
            database.AddInParameter(commandWrapper, "@ExpireTime", DbType.DateTime, (oEntity.ExpireTime.HasValue ? (object)oEntity.ExpireTime : System.DBNull.Value));

            int results = 0;
            if (transaction != null)
            {
                results = database.ExecuteNonQuery(commandWrapper, transaction);
            }
            else
            {
                results = database.ExecuteNonQuery(commandWrapper);
            }
            oEntity.OriginalUserId = oEntity.UserId;
            oEntity.AcceptChanges();
            return Convert.ToBoolean(results);
        }

        public void BulkInsert(string compId, DbTransaction transaction, object entities)
        {
            IEnumerable enumList = entities as IEnumerable;
            if (enumList == null)
                throw new InvalidValueException("entities is not enumerable");

            System.Data.SqlClient.SqlBulkCopy bulkCopy = null;

            if (transaction != null)
            {
                System.Data.SqlClient.SqlConnection cnx = transaction.Connection as System.Data.SqlClient.SqlConnection;
                System.Data.SqlClient.SqlTransaction sqltransaction = transaction as System.Data.SqlClient.SqlTransaction;
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, sqltransaction); //, null);
            }
            else
            {
                bulkCopy = new System.Data.SqlClient.SqlBulkCopy(
                    ConnectionSetting.GetSqlConnection(Core.ApplicationContext.DataConnectionString, compId).ConnectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
            }

            bulkCopy.BulkCopyTimeout = 360;
            bulkCopy.DestinationTableName = "ApiUserToken";

            DataTable dataTable = new DataTable();
            DataColumn col0 = dataTable.Columns.Add("UserID", typeof(System.Int64));
            col0.AllowDBNull = false;
            DataColumn col1 = dataTable.Columns.Add("RefreshToken", typeof(System.String));
            col1.AllowDBNull = true;
            DataColumn col2 = dataTable.Columns.Add("IssueTime", typeof(System.DateTime));
            col2.AllowDBNull = true;
            DataColumn col3 = dataTable.Columns.Add("ExpireTime", typeof(System.DateTime));
            col3.AllowDBNull = true;

            bulkCopy.ColumnMappings.Add("UserID", "UserID");
            bulkCopy.ColumnMappings.Add("RefreshToken", "RefreshToken");
            bulkCopy.ColumnMappings.Add("IssueTime", "IssueTime");
            bulkCopy.ColumnMappings.Add("ExpireTime", "ExpireTime");

            IEnumerator list = enumList.GetEnumerator();
            if (list == null)
                throw new InvalidOperationException("Unable to enumerate entity list");
            list.Reset();
            while (list.MoveNext())
            {
                ApiUserTokenBase entity = list.Current as ApiUserTokenBase;
                if (entity.EntityState != EntityState.Added)
                    continue;
                DataRow row = dataTable.NewRow();
                row["UserID"] = entity.UserId;
                row["RefreshToken"] = entity.RefreshToken;
                row["IssueTime"] = entity.IssueTime.HasValue ? (object)entity.IssueTime : System.DBNull.Value;
                row["ExpireTime"] = entity.ExpireTime.HasValue ? (object)entity.ExpireTime : System.DBNull.Value;

                dataTable.Rows.Add(row);
            }

            // send the data to the server		
            bulkCopy.WriteToServer(dataTable);
            // update back the state
            list.Reset();
            while (list.MoveNext())
            {
                IEntity entity = list.Current as IEntity;
                if (entity.EntityState != EntityState.Added)
                    continue;
                entity.AcceptChanges();
            }
        }

        #endregion

        #endregion "IDataProvider"
    }
}

